<?php

$array = array();

$array['element'] = array();
$array['element']['persistentmembers'] = array();
$array['element']['persistentmembers']['value'] = array('no','yes');
$array['element']['persistentmembers']['default'] = 'yes';
$array['element']['persistentmembers']['set'] = true;

$array['element']['autofill'] = array();
$array['element']['autofill']['value'] = array('no','yes');
$array['element']['autofill']['default'] = 'no';
$array['element']['autofill']['set'] = true;

$array['element']['monitor-type'] = array();
$array['element']['monitor-type']['value'] = array('','mixmonitor');
$array['element']['monitor-type']['default'] = '';
$array['element']['monitor-type']['set'] = true;

$array['filter'] = array();
$array['filter']['persistentmembers'] = array('bool' => true);

?>
