DELETE FROM tmp_userfeatures;

INSERT INTO tmp_userfeatures (
	id,
	protocol,
	protocolid,
	firstname,
	lastname,
	name,
	number,
	context,
	voicemailid,
	agentid,
	provisioningid,
	ringseconds,
	simultcalls,
	enableclient,
	loginclient,
	passwdclient,
	profileclient,
	enablehint,
	enablevoicemail,
	enablexfer,
	enableautomon,
	callrecord,
	callfilter,
	enablednd,
	enableunc,
	destunc,
	enablerna,
	destrna,
	enablebusy,
	destbusy,
	musiconhold,
	outcallerid,
	mobilephonenumber,
	bsfilter,
	preprocess_subroutine,
	internal,
	commented,
	description)
SELECT
	userfeatures.id,
	userfeatures.protocol,
	userfeatures.protocolid,
	userfeatures.firstname,
	userfeatures.lastname,
	userfeatures.name,
	userfeatures.number,
	CASE WHEN userfeatures.context = 'initconfig' THEN 'xivo-initconfig' ELSE userfeatures.context END,
	NULL,
	NULL,
	userfeatures.provisioningid,
	userfeatures.ringseconds,
	userfeatures.simultcalls,
	userfeatures.enableclient,
	'',
	'',
	'',
	userfeatures.enablehint,
	userfeatures.enablevoicemail,
	userfeatures.enablexfer,
	userfeatures.enableautomon,
	userfeatures.callrecord,
	userfeatures.callfilter,
	userfeatures.enablednd,
	userfeatures.enableunc,
	userfeatures.destunc,
	userfeatures.enablerna,
	userfeatures.destrna,
	userfeatures.enablebusy,
	userfeatures.destbusy,
	userfeatures.musiconhold,
	userfeatures.outcallerid,
	'',
	userfeatures.bsfilter,
	NULL,
	userfeatures.internal,
	userfeatures.commented,
	userfeatures.description
FROM userfeatures;

UPDATE tmp_userfeatures 
SET name = 'dahdi/'||SUBSTR(name,5,LENGTH(name)) 
WHERE name LIKE 'zap/%' AND protocol = 'custom'; 

INSERT INTO tmp_contextnummember (
	context,
	type,
	typeval,
	number)
SELECT
	tmp_userfeatures.context,
	'user',
	tmp_userfeatures.id,
	tmp_userfeatures.number
FROM tmp_userfeatures
WHERE internal = 0;
