#!/usr/bin/make -f
# -*- mode: makefile; coding: utf-8 -*-
#
# $Revision$
# $Date$

include $(NONO_MK)/autobuild.mk
include $(NONO_MK)/autobuild-classic.mk

DEB_PKG = "pf-xivo-cti-webclient"
DEB_TB_DEPS=""

default:

