#! /usr/bin/python
# vim: set fileencoding=utf-8 :
#
# $Revision$
# $Date$
#
# Authors : Thomas Bernard, Corentin Le Gall
#           Proformatique
#           67, rue Voltaire
#           92800 PUTEAUX
#           (+33/0)1.41.38.99.60
#           mailto:technique@proformatique.com
#           (C) 2007 Proformatique
#
# AGI de push de fiche
#

import socket, sys, generefiche, ConfigParser, string, ldap, MySQLdb

class Info:
	def __init__(self, ititle, itype, ivalue, idefvalue):
		self.title = ititle
		self.type = itype
		if ivalue == "":
			self.value = idefvalue
		else:
			self.value = ivalue
	def getTitle(self):
		return self.title
	def getType(self):
		return self.type
	def getValue(self):
		return self.value

# \brief Logs a message into the Asterisk CLI
def log_agi(message):
	print "VERBOSE \"" + "xivo_push : " + message + "\""
	return 0

# \brief Returns the kind of database
def get_dbkind():
	global config
	try:
		config.readfp(open("/etc/asterisk/xivo_push.conf"))
	except:
		try:
			config.readfp(open("xivo_push.conf"))
		except:
			log_agi("no xivo_push.conf file found")
			sys.exit(2)
	try:
		databasekind = config.get('general', 'db')
	except:
		databasekind = ""
	return databasekind





config = ConfigParser.ConfigParser()
databasekind = get_dbkind()

if databasekind == "ldap":
	LDAP_HOST = config.get('general', 'host')
	LDAP_PORT = config.get('general', 'port')
	LDAP_USER = config.get('general', 'user')
	LDAP_PASS = config.get('general', 'pass')
	LDAP_BASE = config.get('general', 'dbname')

	class myldap:
		def __init__(self):
			try:
				self.l = ldap.initialize("ldap://%s:%s" %(LDAP_HOST, LDAP_PORT))
				self.l.protocol_version = ldap.VERSION3
				self.l.simple_bind_s(LDAP_USER, LDAP_PASS)

			except ldap.LDAPError, e:
				print e
				sys.exit()

		def getldap(self, filter, attrib):
			try:
				resultat = self.l.search_s(LDAP_BASE, ldap.SCOPE_SUBTREE, filter, attrib)
				return resultat
			except ldap.LDAPError, e:
				print e

elif databasekind == "mysql":
	try:
		con = MySQLdb.connect(host = config.get('general', 'host'),
				      port = int(config.get('general', 'port')),
				      user = config.get('general', 'user'),
				      passwd = config.get('general', 'pass'),
				      db = config.get('general', 'dbname'))
		cursor = con.cursor()
	except Exception, e:
		log_agi("Connection to MySQL failed")

field = {}
daymsg = ""
homepage = ""
mail = ""
urlpicture = ""

#print sys.argv[0], len(sys.argv)
if len(sys.argv) < 6:
	print "Usage :", sys.argv[0], "<server> <port> <proto> <user> <callerid> [<msgext>]"
	sys.exit(1)
else:
	shost = sys.argv[1]
	sport = int(sys.argv[2])
	proto = sys.argv[3]
	exten = sys.argv[4]
	callerid = sys.argv[5]
	user = proto + exten
	if len(sys.argv) > 6: msgext = sys.argv[6]
	else: msgext = ""


if databasekind == "ldap":
	result = myldap().getldap("(|(telephonenumber=%s)(mobile=%s)(pager=%s))" %(callerid,callerid,callerid),
				  ['cn','mail'])
	try:
		r = result[0][1]['cn'][0]
		mail = result[0][1]['mail'][0]
		(field["name"], field["firstname"]) = r.split()
		sys.stdout.write("SET CALLERID \"%s\"\n" %r)
	except:
		print "No callerid from OX"
elif databasekind == "mysql":
	table = config.get('general', 'dbtable')
	sql = "select * from " + table + " where appelant REGEXP '" + callerid + "';"
	cursor.execute(sql)
	results = cursor.fetchall()
	con.close()
	if len(results) > 0:
		x = results[0]
	try:
		field["fullnumber"] = x[0]
		field["agency"]     = x[1]
		field["refnumber"]  = x[2]
		field["name"]       = x[3]
		field["zipcode"]    = x[4]
		field["town"]       = x[5]
		field["medal"]      = x[6]
	except Exception, e:
		log_agi("Customer not found in mysql db")
		if len(callerid) == 9:
			field["fullnumber"] = callerid
		else:
			field["fullnumber"] = ""

	if len(field["fullnumber"]) == 9:
		tmpnum = "0" + field["fullnumber"][0] + "." + \
			 field["fullnumber"][1] + field["fullnumber"][2] + "." + \
			 field["fullnumber"][3] + field["fullnumber"][4] + "." + \
			 field["fullnumber"][5] + field["fullnumber"][6] + "." + \
			 field["fullnumber"][7] + field["fullnumber"][8]
		field["fullnumber"] = tmpnum


liste = []
items = config.items("fiche")
items.sort()
for field_to_display in items:
	# a "/" character splits the order of the field in the displayed popup
	# and its kind
	if field_to_display[0].find("|") >= 0:
		kindoffield = field_to_display[0].split("|")[1]
		argum = field_to_display[1].split("|")[0]
		defaultvalue = field_to_display[1].split("|")[1]
		if kindoffield == "callerid":
			liste.append(Info(argum, 'phone', callerid, defaultvalue))
		elif kindoffield == "picture":
			try:
				urlpicture = config.get('photo', callerid)
			except:
				urlpicture = defaultvalue
			liste.append(Info(argum, 'picture', urlpicture, defaultvalue))
		elif kindoffield == "mail":
			liste.append(Info(argum, 'url', 'mailto:' + mail, 'mailto:' + defaultvalue))
		elif kindoffield == "homepage":
			liste.append(Info(argum, 'url', homepage, defaultvalue))
		elif kindoffield == "daymsg":
			liste.append(Info(argum, 'text', '<b>' + defaultvalue + '</b>', ""))
		else:
			if kindoffield in field:
				value = field[kindoffield]
			else:
				value = ""
			liste.append(Info(argum, 'text', value, defaultvalue))


# first connect to the server to get ip, port of the client
z = generefiche.getuserlocation(shost, sport, user)
if z == None:
	log_agi("Could not localize user " + user)
	sys.exit(3)
sessionid = z.get('sessionid')
clientaddress = z.get('address')
clientstate = z.get('state')

if clientstate == "available":
	print "SET VARIABLE STATUS 0"
	fiche = generefiche.Fiche(sessionid)
	fiche.setmessage(msgext)
	for x in liste:
		fiche.addinfo(x.getTitle(), x.getType(), x.getValue())

	#connect to the client and send the stuff !
	print "Sending Profile"
	if fiche.sendtouser(clientaddress):
		print "Profile sent"
	else:
		log_agi("Could not send profile to user")

elif clientstate == "away":
	print "SET VARIABLE STATUS 1"
elif clientstate == "donotdisturb":
	print "SET VARIABLE STATUS 2"
elif clientstate == "outtolunch":
	pass
	#print "SET VARIABLE STATUS 2"
elif clientstate == "berightback":
	pass
	#print "SET VARIABLE STATUS 2"
else:
	print "unknown client state"

print "availability is currently :", clientstate

sys.stdout.flush()
sys.stderr.flush()

