#! /usr/bin/python
# vim: set fileencoding=utf-8 :
#
# $Revision$
# $Date$
#
# Authors : Thomas Bernard, Corentin Le Gall
#           Proformatique
#           67, rue Voltaire
#           92800 PUTEAUX
#           (+33/0)1.41.38.99.60
#           mailto:technique@proformatique.com
#           (C) 2007 Proformatique
#
# AGI de push de fiche
#

## \mainpage
# \section section_1 XIVO pusher AGI
#
## \file xivo_push
# \brief XIVO CTI pushing AGI
#
## \namespace xivo_push
# \brief XIVO CTI pushing AGI
#

import socket, sys, generefiche, ConfigParser, string, ldap, MySQLdb, sqlite

## \class Info
class Info:
	def __init__(self, ititle, itype, ivalue):
		self.title = ititle
		self.type = itype
		self.value = ivalue
	def getTitle(self):
		return self.title
	def getType(self):
		return self.type
	def getValue(self):
		return self.value

## \class myLDAP
class myLDAP:
	def __init__(self, ihost, iport, iuser, ipass):
		try:
			self.l = ldap.initialize("ldap://%s:%s" %(ihost, iport))
			self.l.protocol_version = ldap.VERSION3
			self.l.simple_bind_s(iuser, ipass)
			
		except ldap.LDAPError, e:
			print e
			sys.exit()

	def getldap(self, ibase, filter, attrib):
		try:
			resultat = self.l.search_s(ibase,
						   ldap.SCOPE_SUBTREE,
						   filter,
						   attrib)
			return resultat
		except ldap.LDAPError, e:
			print e


## \brief Secures an output string for the AGI VERBOSE
# \param s string to secure
def agi_escape_string(s):
       return s.replace('\\', '\\\\').replace('"', '\\"').replace('\n', ' ')


## \brief Logs a message into the Asterisk CLI
# \param txt message to send to the CLI
def print_verbose(txt):
	print "VERBOSE \"xivo_push : %s\"" % agi_escape_string(txt)


## \brief Returns the kind of database
# \param cfg
def get_dbkind(cfg):
	try:
		dbkind = cfg.get('general', 'db')
	except:
		dbkind = ""
	return dbkind


## \brief Returns informations fetched from the LDAP database
# \param config
# \param cid
def get_ldap_infos(config, cid):
	[callid, mail, name, firstname, company] = ["", "", "", "", ""]
	ldapid = myLDAP(config.get('general', 'host'),
			config.get('general', 'port'),
			config.get('general', 'user'),
			config.get('general', 'pass'))
	result = ldapid.getldap(config.get('general', 'dbname'),
				"(|(telephonenumber=%s)(mobile=%s)(pager=%s))" %(cid,cid,cid),
				['cn','mail','sn','givenName','o'])
	try:
		who = result[0][1]
		if 'cn' in who.keys():        callid    = who['cn'][0]
		if 'mail' in who.keys():      mail      = who['mail'][0]
		if 'givenName' in who.keys(): firstname = who['givenName'][0]
		if 'sn' in who.keys():        name      = who['sn'][0]
		if 'o' in who.keys():         company   = who['o'][0]
		sys.stdout.write("SET CALLERID \"%s\"\n" %r)
	except:
		print "No callerid from OX"
	return [callid, mail, name, firstname, company]


## \brief Returns informations fetched from the MySQL database
# \param config configuration informations
# \param cid callerid requested
def get_mysql_infos(config, cid):
	results = []
	try:
		conn = MySQLdb.connect(host = config.get('general', 'host'),
				      port = int(config.get('general', 'port')),
				      user = config.get('general', 'user'),
				      passwd = config.get('general', 'pass'),
				      db = config.get('general', 'dbname'))
		cursor = conn.cursor()

		searchname = config.get('general', 'dbmatch')
		table = config.get('general', 'dbtable')
		sql = "SELECT * FROM %s WHERE %s REGEXP '%s' LIMIT 1;" %(table,searchname,cid)
	        cursor.execute(sql)
		results = [cursor.fetchone()] # vs. fetchall() if needed
		conn.close()

	except Exception, e:
		log_agi("Connection to MySQL failed")

	return results


## \brief Returns informations fetched from the sqlite database
# \param config configuration informations
# \param cid callerid requested
def get_sqlite_infos(config, cid):
	results = []
	try:
		conn = sqlite.connect(db = config.get('general', 'dbname'))
		cursor = conn.cursor()

		searchname = config.get('general', 'dbmatch')
		table = config.get('general', 'dbtable')
		sql = "SELECT * FROM %s WHERE %s = '%s' LIMIT 1;" %(table,searchname,cid)
	        cursor.execute(sql)
		results = [cursor.fetchone()] # vs. fetchall() if needed
		conn.close()

	except Exception, e:
		log_agi("Connection to sqlite failed")

	return results


## \brief fills the variable fields according to the recetived data
# \param callerid
# \param x
def set_fields_from_resultline(callerid, x):
	field = {}
	try:
		field["fullnumber"] = x[0]
		field["agency"]     = x[1]
		field["refnumber"]  = x[2]
		field["name"]       = x[3]
		field["zipcode"]    = x[4]
		field["town"]       = x[5]
		field["medal"]      = x[6]
	except Exception, e:
		log_agi("Customer not found in mysql db")
		if len(callerid) == 9:
			field["fullnumber"] = callerid
		else:
			field["fullnumber"] = ""

	if len(field["fullnumber"]) == 9:
		tmpnum = "0" + field["fullnumber"][0] + "." + \
			 field["fullnumber"][1] + field["fullnumber"][2] + "." + \
			 field["fullnumber"][3] + field["fullnumber"][4] + "." + \
			 field["fullnumber"][5] + field["fullnumber"][6] + "." + \
			 field["fullnumber"][7] + field["fullnumber"][8]
		field["fullnumber"] = tmpnum

	return field


## \brief Builds the contents of the Sheet according to titles and default values
# \param items
# \param formats
# \param flds
def make_fields(items, formats, flds):
	liste = []
	for field_to_display in items:
		# a "/" character splits the order of the field in the displayed popup
		# and its kind
		if field_to_display[0].find("|") >= 0:
			kindoffield  = field_to_display[0].split("|")[1]

			fieldtype    = field_to_display[1].split("|")[0]
			argum        = field_to_display[1].split("|")[1]
			defaultvalue = field_to_display[1].split("|")[2]

			prestr = ""
			poststr = ""
			if kindoffield in formats.keys():
				prestr = formats[kindoffield].split("|")[0]
				poststr = formats[kindoffield].split("|")[1]
			value = prestr + defaultvalue + poststr
			if kindoffield in flds:
				if flds[kindoffield] != "":
					value = prestr + flds[kindoffield] + poststr
			liste.append(Info(argum, fieldtype, value))
	return liste


# ==============================================================================
# Main Code starts here
# ==============================================================================

if len(sys.argv) < 6:
	print "Usage :", sys.argv[0], "<server> <port> <proto> <user> <callerid> [<msgext>]"
	sys.exit(1)
else:
	shost = sys.argv[1]
	sport = int(sys.argv[2])
	proto = sys.argv[3]
	exten = sys.argv[4]
	callerid = sys.argv[5]
	user = proto + exten
	if len(sys.argv) > 6: msgext = sys.argv[6]
	else: msgext = ""

# 1/N : connects to the server to get IP address and port of the client
z = generefiche.getuserlocation(shost, sport, user)
if z == None:
	log_agi("Could not localize user %s" %user)
	sys.exit(3)
sessionid = z.get('sessionid')
clientaddress = z.get('address')
clientstate = z.get('state')

# 2/N : opens the xivo_push.conf config file
config = ConfigParser.ConfigParser()
try:
	config.readfp(open("/etc/asterisk/xivo_push.conf"))
except:
	try:
		config.readfp(open("xivo_push.conf"))
	except:
		log_agi("no xivo_push.conf file found")
		sys.exit(2)

# 3/N : reads the kind of database and the sheet's format
databasekind = get_dbkind(config)
fitems = config.items("fiche")
fitems.sort()
fformats = {}
if "formats" in config.sections() :
	for x in config.items("formats"):
		fformats[x[0]] = x[1]

# 4/N : reads the informations from the database and fills them into one ore more lists

liste = []
fields = {}

if databasekind == "ldap":
	fields["req_cid"] = callerid
	fields["callidname"], fields["mail"], fields["name"], fields["firstname"], fields["company"] = get_ldap_infos(config, callerid)
	if callerid in config.options('photo'):
		fields["picture"] = config.get('photo', callerid)
	liste = make_fields(fitems, fformats, fields)
elif databasekind == "mysql" or databasekind == "sqlite":
	listes = []
	if databasekind == "mysql":
		results = get_mysql_infos(config, callerid)
	if databasekind == "sqlite":
		results = get_sqlite_infos(config, callerid)
	log_agi("%d result(s) found for %s" %(len(results),callerid))
	if len(results) > 0:
		for z in xrange(len(results)):
			fields = set_fields_from_resultline(callerid, results[z])
			fields["req_cid"] = callerid
			liste = make_fields(fitems, fformats, fields)
			listes.append(liste)
	else:
		fields["req_cid"] = callerid
		liste = make_fields(fitems, fformats, fields)
else:
	log_agi("Database type %s not supported" %databasekind)
	sys.exit(3)

# 5/N : sends the sheet to the connected peer

if clientstate == "available":
	print "SET VARIABLE STATUS 0"

	# this could be replaced by a loop if needed
	fiche = generefiche.Fiche(sessionid)
	fiche.setmessage(msgext)
	for x in liste:
		fiche.addinfo(x.getTitle(), x.getType(), x.getValue())
	# connect to the client and send the stuff !
	print "Sending Profile"
	if fiche.sendtouser(clientaddress):
		print "Profile sent"
	else:
		log_agi("Could not send profile to user")

elif clientstate == "away":
	print "SET VARIABLE STATUS 1"
elif clientstate == "donotdisturb":
	print "SET VARIABLE STATUS 2"
elif clientstate == "outtolunch":
	pass
	#print "SET VARIABLE STATUS 2"
elif clientstate == "berightback":
	pass
	#print "SET VARIABLE STATUS 2"
else:
	log_agi("Unknown user's availability status : %s" %clientstate)

print "availability is currently :", clientstate

sys.stdout.flush()
sys.stderr.flush()

