#!/usr/bin/python

import os
import sys
import logging
import logging.handlers
import traceback
import ConfigParser

from xivo import network

CFGFILE = '/etc/pf-xivo/routes'

logger = logging.getLogger('xivo-routes')
logger.addHandler(logging.handlers.SysLogHandler())
logger.setLevel(logging.INFO)

if __name__ == '__main__':
    iface = os.environ['IFACE']
    mode  = os.environ['MODE']  # start/stop

    logger.info("XiVO custom routes on %s interface (mode=%s)" % (iface, mode))

    if mode != 'start':
        sys.exit(0)

    cfg = ConfigParser.ConfigParser()
    cfg.read(CFGFILE)

    if not cfg.has_section(iface):
        sys.exit(0)

    for name, rule  in cfg.items(iface):
        logger.info("  . applying *%s* rule" % name)
        print name, rule
        rule = rule.split(';')
        if len(rule) != 3:
            continue

        rule.append(iface)
        try:
            (ret, verbose) = network.route_set(*rule)
        except Exception, e:
            traceback.print_exc()

