<?php

#
# XiVO Web-Interface
# Copyright (C) 2010  Proformatique <technique@proformatique.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

$array = array();

$array['element'] = array();

$array['element']['records_path'] = array();
$array['element']['records_path']['default'] = '';

$array['element']['records_announce'] = array();
$array['element']['records_announce']['default'] = '';

$array['element']['purge_syst_tagged_delay'] = array();
$array['element']['purge_syst_tagged_delay']['default'] = '';

$array['element']['purge_syst_tagged_at'] = array();
$array['element']['purge_syst_tagged_at']['default'] = '';

$array['element']['purge_syst_untagged_delay'] = array();
$array['element']['purge_syst_untagged_delay']['default'] = '';

$array['element']['purge_syst_untagged_at'] = array();
$array['element']['purge_syst_untagged_at']['default'] = '';

$array['element']['purge_punct_delay'] = array();
$array['element']['purge_punct_delay']['default'] = '';

$array['element']['purge_punct_at'] = array();
$array['element']['purge_punct_at']['default'] = '';

$array['element']['svichoices'] = array();
$array['element']['svichoices']['default'] = '';

$array['element']['svientries'] = array();
$array['element']['svientries']['default'] = '';

$array['element']['svivariables'] = array();
$array['element']['svivariables']['default'] = '';


$array['filter'] = array();

?>
