#!/usr/bin/make -f
# -*- mode: makefile; coding: utf-8 -*-
#
# $Revision$
# $Date$

include $(NONO_MK)/autobuild.mk
include $(NONO_MK)/autobuild-classic.mk

DEB_PKG := python-yaml
TARBALL_DIR := $(realpath $(MODULE_PATH)/pyyaml)
XIVO_REV := $(shell cat $(realpath $(MODULE_PATH))/VERSION)

default:
