#!/bin/sh

# Xivo 0.3 - Handle lighttpd server.
# Copyright (C) 2006 Richard Braun <rbraun@proformatique.com>
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

set -e

PATH=/sbin:/bin:/usr/sbin:/usr/bin
pidfile=/var/run/lighttpd.pid
daemon=lighttpd
binpath=/usr/sbin/$daemon
conffile=/etc/lighttpd.conf
user=www
group=www

test -x $binpath || exit 0

# usage: running <pidfile>
running()
{
  if [ -f "$1" ]; then
    return 0
  fi

  return 1
}

start_lighttpd()
{
  echo -n "starting lighttpd... "
  if ! running $pidfile; then
    start-stop-daemon -q \
                      -x $binpath \
                      -p $pidfile \
                      -S \
                      -- \
                      -f $conffile
    echo "done"
  else
    echo "lighttpd already running"
  fi
}

stop_lighttpd()
{
  echo -n "stopping lighttpd... "
  if running $pidfile; then
    start-stop-daemon -q \
                      -x $binpath \
                      -p $pidfile \
                      -K
    sleep 1
    rm -f $pidfile
    echo "done"
  else
    echo "lighttpd not running"
  fi
}

case "$1" in
  start)
    start_lighttpd
    ;;
  stop)
    stop_lighttpd
    ;;
  restart)
    stop_lighttpd
    start_lighttpd
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
