#!/bin/bash
# Small script to create a tar.gz file that can be extracted easily on a
# XiVO 1.1 with a "tar xvf <file> -C /"

OUTFILE=qlogc.tar.gz

if [[ ! -d scripts || ! -d src || ! -d etc ]]; then
    echo "You must run this script in the project root..." >&2
    exit 1
fi

TMPDIR=$(mktemp -d)

# copy scripts
mkdir -p "$TMPDIR/usr/bin"
cp --preserve=mode scripts/qlogc "$TMPDIR/usr/bin"

# copy configuration files
mkdir -p "$TMPDIR/etc/pf-xivo"
cp etc/qlog-client.conf "$TMPDIR/etc/pf-xivo"

mkdir -p "$TMPDIR/etc/cron.d"
cp etc/cron.d/pf-xivo-qlog-client "$TMPDIR/etc/cron.d/pf-xivo-qlog-client"

# copy python modules
mkdir -p "$TMPDIR/var/lib/python-support/python2.5/qlogclient"
rsync -rp --exclude '.*' --exclude '*.pyc' src/ "$TMPDIR/var/lib/python-support/python2.5"

# create state dir
mkdir -p "$TMPDIR/var/lib/pf-xivo-qlog-client"

# create package
cd "$TMPDIR"
tar caf "$OLDPWD/$OUTFILE" *
cd "$OLDPWD"

echo "Created file $OUTFILE"

rm -r "$TMPDIR"
