<?php

#
# XiVO Web-Interface
# Copyright (C) 2006-2009  Proformatique <technique@proformatique.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

define('DWHO_LABEL','DWHO');

define('DWHO_IPV4_NETMASK_BIT',1);
define('DWHO_IPV4_NETMASK_DOTDEC',2);
define('DWHO_IPV4_NETMASK_ALL',(DWHO_IPV4_NETMASK_BIT | DWHO_IPV4_NETMASK_DOTDEC));

define('DWHO_ENT_APOSTROPHE',1);
define('DWHO_ENT_NOSPECIALCHARS',8);

?>
