#!/usr/bin/python
#
# Authors : Sylvain Boily, Guillaume Knispel
#           Proformatique
#           67, rue Voltaire
#           92800 PUTEAUX
#           (+33/0)1.41.38.99.60
#           mailto:technique@proformatique.com
#           (C) 2007 Proformatique
#

__version__ = "$Revision: 1136 $ $Date: 2007-07-13 19:49:46 +0200 (Fri, 13 Jul 2007) $"
__license__ = """
    Copyright (C) 2007, Proformatique

    This software is free software; you can redistribute it and/or
    modify it under the terms of the GNU Lesser General Public
    License as published by the Free Software Foundation; either
    version 2.1 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public
    License along with this library; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
"""

import xivo.to_path

import sys
from agi import *

import string, urllib

agi = AGI()

number = agi.env['agi_callerid']
channel = agi.get_variable('CHANNEL')
key = 'SAD8Z8ZR53D1FZEER872N2QA873'
website = 'http://monbazile.fr/connect.php'
session = sys.argv[1]
url = "%s?N=%s&I=%s&W=%s&C=%s" % (website, number, key, session, channel)

agi.verbose(url)

response = urllib.urlopen(url).read()

if response == "ok":
	agi.set_variable('BAZILE_NUM', 1)
	agi.verbose('Bazile connu')
else:
	agi.set_variable('BAZILE_NUM', 0)
	agi.verbose('Bazile inconnu')
