#!/usr/bin/python

__version__ = "$Revision$ $Date$"
__license__ = """
    Copyright (C) 2007-2010  Proformatique

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License along
    with this program; if not, write to the Free Software Foundation, Inc.,
    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
"""

import sys
from xivo.agi import *

import string
import urllib

agi = AGI()

number = agi.env['agi_callerid']
channel = agi.get_variable('CHANNEL')
key = 'SAD8Z8ZR53D1FZEER872N2QA873'
website = 'http://monbazile.fr/connect.php'
session = sys.argv[1]
url = "%s?N=%s&I=%s&W=%s&C=%s" % (website, number, key, session, channel)

agi.verbose(url)

response = urllib.urlopen(url).read()

if response == "ok":
	agi.set_variable('BAZILE_NUM', 1)
	agi.verbose('Bazile connu')
else:
	agi.set_variable('BAZILE_NUM', 0)
	agi.verbose('Bazile inconnu')
