#!/bin/sh
# $Revision$
# $Date$
#
# Startup daemon script for xivo_daemon_bazile
#

DAEMON=/usr/sbin/xivo_daemon_bazile
PIDFILE="/var/run/xivo_daemon_bazile.pid"

# TODO :
# - section LSB
# - start stop daemon

case "$1" in
  start)
	if [ -e $PIDFILE ] ; then
	    echo "A xivo_daemon_bazile daemon PID file" $PIDFILE "was found. Nothing new started."
	    exit 1
	else
	    echo "Starting xivo_daemon_bazile daemon."
	    $DAEMON
	fi
	;;
  stop)
	if ! [ -e $PIDFILE ] ; then
	    echo "No xivo_daemon_bazile daemon PID file" $PIDFILE "found."
	    exit 1
	else
	    echo "Stopping xivo_daemon_bazile daemon."
	    DAEMONPID=$(cat $PIDFILE | tr -d '[:blank:]')
	    echo "PID =" $DAEMONPID
	    kill $DAEMONPID
	    rm $PIDFILE
	fi
	;;
  force-reload)
	if ! [ -e $PIDFILE ] ; then
	    echo "No xivo_daemon_bazile daemon PID file" $PIDFILE "found."
	    exit 1
	else
	    echo "Reloading xivo_daemon_bazile daemon configuration."
	    DAEMONPID=$(cat $PIDFILE | tr -d '[:blank:]')
	    echo "PID =" $DAEMONPID
	    kill -HUP $DAEMONPID
	    rm $PIDFILE
	fi
	;;
  restart)
	$0 stop
	$0 start
	;;
  *)
	echo "Usage: $0 {start|stop|force-reload|restart}"
	exit 1
	;;
esac

exit 0

