#!/bin/bash

. ./sources.pkg

##########################################################################

usage()
{
	echo "Usage: $0 <version>"
}

UPVERSION=$1
if [ -z "${UPVERSION}" ]; then
	usage
	exit 1
fi

if [ -n "${DFSG_EXCLUDE_PATTERNS}" ]; then
	FILENAME="${PKG_NAME}_${UPVERSION}+dfsg.orig.tar.gz"
else
	FILENAME="${PKG_NAME}_${UPVERSION}.orig.tar.gz"
fi

mkdir -p ${DEST_PATH}

if [ -e "${DEST_PATH}/${FILENAME}" ]; then
	echo "A tarball already exist for this version ; remove it if you want to regenerate."
	exit 0
fi

UPFILENAME="${PKG_NAME}_${UPVERSION}.orig.tar.gz"
URL="${BASE_URL}/${TARBALL_PREFIX}${UPVERSION}.tar.gz"

echo "Downloading ${UPFILENAME} from ${URL}"
wget -nv -T10 -t3 -O ${DEST_PATH}/${UPFILENAME} ${URL}
if [ $? != 0 ]; then
	rm -f ${DEST_PATH}/${UPFILENAME}
	echo "Could not find tarball."
	exit 2
fi

if [ -n "${DFSG_EXCLUDE_PATTERNS}" ]; then
	echo "Repacking as DFSG-free..."
	DIR="${DEST_PATH}/${PKG_NAME}-${UPVERSION}.tmp"
	rm -rf ${DIR}
	mkdir -p ${DIR}
	(
		cd ${DIR}
		tar xfz ../${UPFILENAME}
		if [ -e "${SRC_DIR_PREFIX}${UPVERSION}" ]; then
			(
			cd ${SRC_DIR_PREFIX}${UPVERSION}
			rm -rf ${DFSG_EXCLUDE_PATTERNS}
			)
			tar cfz ../${FILENAME} ${SRC_DIR_PREFIX}${UPVERSION}
		else
			echo "Source tarball layout changed. Check by yourself in '${DEST_PATH}/${PKG_NAME}-${UPVERSION}.tmp/'."
			exit 2
		fi
	)
	rm -rf ${DIR}
	rm -f ${DEST_PATH}/${UPFILENAME}
else
	if [ "${UPFILENAME}" != "${FILENAME}" ]; then
		mv ${DEST_PATH}/${UPFILENAME} ${DEST_PATH}/${FILENAME}
	fi
fi

echo "Done !"

