#!/usr/bin/make -f
# -*- mode: makefile; coding: utf-8 -*-
#
# $Revision$
# $Date$

include $(NONO_MK)/autobuild.mk

DEB_PKG = "dahdi-tools"

SRCVER = $(shell cat $(MODULE_PATH)/SOURCE-VERSION)
TARBALL_NAME = "dahdi-tools_$(SRCVER).orig.tar.gz"
XIVO_REV = $(SRCVER)+pf.$(MAINREV)~svn$(SVNREV)


default:

do-tarball::
	cp $(MODULE_PATH)/tarballs/$(TARBALL_NAME) $(DEB_DESTDIR)/$(DEB_PKG)_$(XIVO_REV).orig.tar.gz

