#!/bin/sh

# Xivo 0.1 - Fill /dev/zap, and configure the Zaptel driver.
# Copyright (C) 2006 Richard Braun <rbraun@proformatique.com>
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

set -e

PATH=/sbin:/bin:/usr/sbin:/usr/bin
conffile=/etc/zaptel.conf

start_zaptel()
{
  echo -n "creating and filling /dev/zap... "
  mkdir /dev/zap
  cd /dev/zap

  # mdev ins't able to fill /dev/zap, it creates /dev/zapxxx files.
  for i in $(seq 32) ctl channel timer pseudo; do
    ln -s /dev/zap$i $i
  done

  echo "done"

  echo "configuring the Zaptel driver from $conffile..."
  ztcfg -c $conffile
  echo "done"
}

case "$1" in
  start)
    start_zaptel
    ;;
  stop)
    :
    ;;
  *)
    echo "usage: $0 {start|stop (ignored)}"
    exit 1
    ;;
esac

exit 0
