#!/bin/bash

# /sbin/installkernel replacement, which doesn't call mkboot and can
# evolve on its own when a special feature is needed.
# Copyright (C) 2006 Richard Braun <rbraun@proformatique.com>
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

set -e

version=$1
zimage=$2
system_map=$3
directory=$4

if [ -z "$version" ] || [ -z "$zimage" ] || [ -z "$system_map" ] || \
   [ -z "$directory" ]; then
  echo "usage: $0 version zImage System.map directory"
  exit 1
fi

cp $zimage $directory/vmlinux-$version
cp $system_map $directory/System.map-$version
cd $directory
ln -s vmlinux-$version vmlinux
ln -s System.map-$version System.map
