#!/usr/bin/python
__version__ = "$Revision$ $Date$"
__license__ = """
    Copyright (C) 2006-2010  Proformatique <technique@proformatique.com>

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""

import socket

try:
        astup = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        astup.setsockopt(socket.SOL_SOCKET, socket.SO_BROADCAST, 1)
        dport = 5006
        tosend = 'asterisk-1.4'
        # send via loopback interface
        astup.sendto(tosend, ('127.0.0.1', dport))
        # send via default interface
        astup.sendto(tosend, ('255.255.255.255', dport))
except:
        pass
