#!/usr/bin/python

__version__ = "$Revision$ $Date$"
__license__ = """
    Copyright (C) 2006, 2007, 2008  Proformatique

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License along
    with this program; if not, write to the Free Software Foundation, Inc.,
    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA..
"""

import sys
from xivo import xivo_helpers

if len(sys.argv) != 4:
    raise ValueError, "Missing args!"

cursor = xivo_helpers.db_connect().cursor()
cursor.query("UPDATE voicemail "
             "SET password = %s "
             "WHERE context = %s "
             "AND mailbox = %s",
             parameters = (sys.argv[3], sys.argv[1], sys.argv[2]))
xivo_helpers.db_close()
