#!/usr/bin/python
__version__ = ""
__license__ = """
    Copyright (C) 2010  Proformatique <technique@proformatique.com>

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""

import sys
from xivo import OrderedConf
from xivo import xivo_helpers

cursor = xivo_helpers.db_connect().cursor()

cursor.query("SELECT ${columns} FROM userqueueskill u, userfeatures uf, queueskill s WHERE u.userid = uf.id AND u.skillid = s.id", ('uf.id', 's.name', 'u.weight'))
res = cursor.fetchall()

section = None
for r in res:
	nsection = "%d" % r['uf.id']

	if nsection != section:		
		print "\n[%s]" % nsection
		section = nsection

	print "%s = %s" % (r['s.name'], r['u.weight'])

