#!/usr/bin/python
__version__ = "$Revision$ $Date$"
__license__ = """
    Copyright (C) 2010-2011  Proformatique <technique@proformatique.com>

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""

import sys
from xivo import OrderedConf
from xivo import xivo_helpers

cursor = xivo_helpers.db_connect().cursor()
section = None

cursor.query("SELECT ${columns} FROM userqueueskill u, userfeatures uf, queueskill s WHERE u.userid = uf.id AND u.skillid = s.id ORDER BY uf.id", ('uf.id', 's.name', 'u.weight'))
res = cursor.fetchall()
for r in res:
	nsection = "%d" % r['uf.id']

	if nsection != section:		
		print "\n[user-%s]" % nsection
		section = nsection

	print "%s = %s" % (r['s.name'], r['u.weight'])



cursor.query("SELECT ${columns} FROM agentqueueskill a, agentfeatures af, queueskill s WHERE a.agentid = af.id AND a.skillid = s.id ORDER BY af.id", ('af.id', 's.name', 'a.weight'))
res = cursor.fetchall()
for r in res:
	nsection = "%d" % r['af.id']

	if nsection != section:		
		print "\n[agent-%s]" % nsection
		section = nsection

	print "%s = %s" % (r['s.name'], r['a.weight'])

