#!/usr/bin/make -f
# -*- mode: makefile; coding: utf-8 -*-
#
# $Revision$
# $Date$

include ../autobuild.mk
include ../autobuild-classic.mk

DEB_PKG="pf-xivo-cti-server"
DEB_TB_DEPS=""
DEB_TAR_EXTRA_OPTIONS="--exclude=*.pyc" "--exclude=Calls" "--exclude=CallBooster.py"

default:
