#!/usr/bin/make -f
# -*- mode: makefile; coding: utf-8 -*-

include $(NONO_MK)/autobuild.mk
include $(NONO_MK)/autobuild-classic.mk

DEB_PKG="pf-xivo-cti-server"
DEB_TB_DEPS=""
DEB_TAR_EXTRA_OPTIONS="--exclude=*.pyc"

default:
