#!/usr/bin/make -f
# -*- mode: makefile; coding: utf-8 -*-
#
# $Revision: 5179 $
# $Date: 2009-01-22 16:00:12 +0100 (Thu, 22 Jan 2009) $

include $(NONO_MK)/autobuild.mk
include $(NONO_MK)/autobuild-classic.mk

DEB_PKG="pf-xivo-queues-logger"
DEB_TB_DEPS=""

default:

