#!/bin/sh

# Xivo 0.2 - Create a suitable environment for passwd (which needs write
# access on the /etc directory).
# Copyright (C) 2006 Richard Braun <rbraun@proformatique.com>
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

atexit()
{
  cd /tmp
  umount newroot/etc
  umount newroot
  rmdir newroot
  exit
}

trap atexit EXIT
trap atexit TERM
trap atexit QUIT
trap atexit STOP
trap atexit INT

cd /tmp
mkdir -p newroot
mount -o bind / newroot
mount -t tmpfs tmpfs newroot/etc
cp -r /etc/* newroot/etc

# Force execution of the real passwd command.
chroot newroot /usr/bin/passwd $@

for file in passwd group shadow gshadow; do
  cat newroot/etc/$file > /mnt/$file
  cat newroot/etc/$file- > /mnt/$file-
done
