#!/bin/sh

# Xivo 0.1 - Mount system critical file systems (e.g. /dev, /sys, /proc).
# Copyright (C) 2006 Richard Braun <rbraun@proformatique.com>
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

set -e

PATH=/sbin:/bin:/usr/sbin:/usr/bin

# Mount a file system.
# 
# usage: do_mount <type> <device> <mount_point> [options]
do_mount()
{
  if [ -d $3 ] && mountpoint -q $3; then
    return
  fi

  options="$4"

  if [ "$options" ]; then
    options="-o $options"
  fi

  echo -n "mounting $3... "
  mkdir -p $3
  mount -n $options -t $1 $2 $3
  echo "done"
}

start_mountsys()
{
  # See /etc/init.d/rcS
  [ -f /var/run/utmp ] && return

  do_mount proc proc /proc
  do_mount sysfs sysfs /sys
  do_mount tmpfs tmpfs /dev
  do_mount devpts devpts /dev/pts "gid=5,mode=620"
  do_mount tmpfs tmpfs /dev/shm
  chmod 1777 /dev/shm
  do_mount tmpfs tmpfs /tmp
}

stop_mountsys()
{
  umount -a -r
}

case "$1" in
  start)
    start_mountsys
    ;;
  stop)
    stop_mountsys
    ;;
  *)
    echo "usage: $0 {start|stop}"
    exit 1
    ;;
esac

exit 0
