#!/bin/sh

# Xivo 0.1 - Main system boot script.
# Copyright (C) 2006 Richard Braun <rbraun@proformatique.com>
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

set -e

PATH=/sbin:/bin:/usr/sbin:/usr/bin

# /var/run/utmp has been arbitrarily chosen to indicate that the boot
# process has already terminated and must not be started again.
[ -f /var/run/utmp ] && return

. /etc/dist

echo
echo "$DIST_NAME $DIST_VERSION booting"
echo

/etc/init.d/mountsys start
/etc/init.d/filldev
/etc/init.d/loadmodules
/etc/init.d/mountfstab start
/etc/init.d/hostname
/etc/init.d/syslogd start
/etc/init.d/klogd start
/etc/init.d/networking start
/etc/init.d/dropbear start
/etc/init.d/zaptel start
/etc/init.d/asterisk start
/etc/init.d/thy start
/etc/init.d/vsftpd start
