#!/bin/sh

# Xivo 0.3 - Reset factory defaults.
# Copyright (C) 2006 Richard Braun <rbraun@proformatique.com>
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

set -e

PATH=/sbin:/bin:/usr/sbin:/usr/bin

sysconf=/sysconf.img.gz
boot_dir=/boot
kernel=vmlinux
system_map=System.map
conf_partition=$(grep ' /mnt ' /etc/fstab | cut -d ' ' -f 1)

cd /

echo -n "resetting kernel and system map... "
mount $boot_dir
cat /$kernel > $boot_dir/$kernel
cat /$system_map > $boot_dir/$system_map
umount $boot_dir
echo "done"

if [ ! -f "$sysconf" ]; then
  echo "factory defaults not found, aborting"
  exit 1
fi

echo "shutting down services..."
/etc/init.d/shutdown
echo "resetting factory defaults, please wait..."
gunzip -c $sysconf | dd of=$conf_partition bs=256k
echo "configuration reset complete, rebooting..."
reboot
