#!/bin/sh

# Xivo 0.2 - Reset factory defaults.
# Copyright (C) 2006 Richard Braun <rbraun@proformatique.com>
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

set -e

PATH=/sbin:/bin:/usr/sbin:/usr/bin

sysconf=/sysconf.img.gz
conf_partition=$(grep ' /mnt ' /etc/fstab | cut -d ' ' -f 1)

cd /
echo "resetting factory defaults, please wait..."

if [ ! -f "$sysconf" ]; then
  echo "factory defaults not found, aborting"
  exit 1
fi

# The shutdown process will take care if stopping services.
umount -l /mnt
gunzip -c $sysconf | dd of=$conf_partition

echo "configuration reset complete, rebooting..."
reboot
