#!/bin/sh

# Xivo 0.1 - System shutdown script.
# Copyright (C) 2006 Richard Braun <rbraun@proformatique.com>
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

PATH=/sbin:/bin:/usr/sbin:/usr/bin

echo
echo "System shutdown in progress"
echo

# Don't call /etc/init.d/networking stop so that network is up when
# processes are killed. SSH processes getting killed will close
# connections automatically.
/etc/init.d/vsftpd stop
/etc/init.d/thy stop
/etc/init.d/asterisk stop
/etc/init.d/dropbear stop
/etc/init.d/klogd stop
/etc/init.d/syslogd stop
/etc/init.d/mountfstab stop
/etc/init.d/mountsys stop
