#!/usr/bin/make -f
# -*- mode: makefile; coding: utf-8 -*-
#
# $Revision$
# $Date$
#
# set PATH and CC to include cross compiling tools for cross compilation, e.g.
# export PATH=/path/to/toolchain/powerpc-linux-gnu/bin:$PATH
# export CC=gcc

include $(NONO_MK)/autobuild.mk
include $(NONO_MK)/autobuild-classic.mk


DEB_PKG="pf-asterisk-res-watchdog"
DEB_TB_DEPS=""
DEB_TAR_EXTRA_OPTIONS="-h"

default:

