#!/usr/bin/python

__version__ = "$Revision$ $Date$"
__license__ = """
    Copyright (C) 2008  Proformatique

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License along
    with this program; if not, write to the Free Software Foundation, Inc.,
    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA..
"""

import sys

from xivo_agid import agid
from xivo_agid.modules import *
from xivo import daemonize

PIDFILE="/var/run/agid.pid"

def log_stderr_and_syslog(x):
	"""
	This function logs the string x to both stderr and the system log.
	The trailing '\\n' of the string to be logged must have been stripped
	"""

	print >> sys.stderr, x
	syslogf(SYSLOG_ERR, x)

if '-d' not in sys.argv:
	agid.debug_enabled = True

if '-f' not in sys.argv:
	daemonize.daemonize(log_stderr_and_syslog, PIDFILE, pidfile_lock = True)

agid.run()
