<?php

$array = array();
$array['index'] = 'index.php';
$array['service/ipbx'] = 'service/ipbx/index.php';
$array['service/ipbx/general_settings/sipprotocol'] = 'service/ipbx/index.php/general_settings/sipprotocol/';
$array['service/ipbx/general_settings/iaxprotocol'] = 'service/ipbx/index.php/general_settings/iaxprotocol/';
$array['service/ipbx/general_settings/voicemail'] = 'service/ipbx/index.php/general_settings/voicemail/';
$array['service/ipbx/general_settings/queues'] = 'service/ipbx/index.php/general_settings/queues/';
$array['service/ipbx/general_settings/sounds'] = 'service/ipbx/index.php/general_settings/sounds/';
$array['service/ipbx/general_settings/musiconhold'] = 'service/ipbx/index.php/general_settings/musiconhold/';
$array['service/ipbx/general_settings/extenfeatures'] = 'service/ipbx/index.php/general_settings/extenfeatures/';
$array['service/ipbx/pbx_settings/users'] = 'service/ipbx/index.php/pbx_settings/users/';
$array['service/ipbx/pbx_settings/groups'] = 'service/ipbx/index.php/pbx_settings/groups/';
$array['service/ipbx/pbx_settings/meetme'] = 'service/ipbx/index.php/pbx_settings/meetme/';
$array['service/ipbx/pbx_settings/queues'] = 'service/ipbx/index.php/pbx_settings/queues/';
$array['service/ipbx/pbx_settings/agents'] = 'service/ipbx/index.php/pbx_settings/agents/';
$array['service/ipbx/call_management/did'] = 'service/ipbx/index.php/call_management/did/';
$array['service/ipbx/trunk_management/sip'] = 'service/ipbx/index.php/trunk_management/sip/';
$array['service/ipbx/trunk_management/iax'] = 'service/ipbx/index.php/trunk_management/iax/';
$array['service/ipbx/system_management/configfiles'] = 'service/ipbx/index.php/system_management/configfiles/';
$array['service/ipbx/system_management/isdncard'] = 'service/ipbx/index.php/system_management/isdncard/';
$array['service/ipbx/system_management/modules'] = 'service/ipbx/index.php/system_management/modules/';
$array['service/ipbx/system_management/manager'] = 'service/ipbx/index.php/system_management/manager/';
$array['service/ipbx/control_system/reload'] = 'service/ipbx/index.php/control_system/reload/';
$array['xivo'] = 'xivo/index.php';
$array['xivo/configuration'] = 'xivo/configuration.php';
$array['xivo/preferences'] = 'xivo/preferences.php';
$array['xivo/help'] = 'xivo/help.php';
$array['xivo/contact'] = 'xivo/contact.php';
$array['xivo/logout'] = 'xivo/logout.php';

?>
