#!/bin/sh

# Xivo 0.1 - Handle vsftpd.
# Copyright (C) 2006 Richard Braun <rbraun@proformatique.com>
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

set -e

PATH=/sbin:/bin:/usr/sbin:/usr/bin
pidfile=/var/run/vsftpd.pid
binpath=/usr/sbin/vsftpd
chrootdir=/var/run/vsftpd

test -x $binpath || exit 0

# usage: running <pidfile>
running()
{
  if [ -f "$1" ]; then
    return 0
  fi

  return 1
}

start_vsftpd()
{
  echo -n "starting vsftpd... "
  mkdir -p -m 755 $chrootdir
  if ! running $pidfile; then
    start-stop-daemon --background \
                      --quiet \
                      --exec $binpath \
                      --pidfile $pidfile \
                      --make-pid \
                      --start
    echo "done"
  else
    echo "vsftpd already running"
  fi
}

stop_vsftpd()
{
  echo -n "stopping vsftpd... "
  if running $pidfile; then
    start-stop-daemon --quiet \
                      --exec $binpath \
                      --pidfile $pidfile \
                      --stop
    rm -f $pidfile
    echo "done"
  else
    echo "vsftpd not running"
  fi
}

reload_vsftpd()
{
  echo -n "reloading vsftpd... "
  if running $pidfile; then
    start-stop-daemon --quiet \
                      --exec $binpath \
                      --pidfile $pidfile \
                      --signal 1 \
                      --stop
    echo "done"
  else
    echo "vsftpd not running"
  fi
}

case "$1" in
  start)
    start_vsftpd
    ;;
  stop)
    stop_vsftpd
    ;;
  reload)
    reload_vsftpd
    ;;
  restart)
    stop_vsftpd
    sleep 1
    start_vsftpd
    ;;
  *)
    echo "usage: $0 {start|stop|reload|restart}"
    exit 1
    ;;
esac

exit 0
