#!/bin/sh

. ./sources.pkg

VER=$(cat SOURCE-VERSION)

echo "Preparing source for ${PKG_NAME}_${VER}"

if [ -n "${DFSG_EXCLUDE_PATTERNS}" ]; then
	FILENAME="${PKG_NAME}_${VER}+dfsg.orig.tar.gz"
else
	FILENAME="${PKG_NAME}_${VER}.orig.tar.gz"
fi

if [ ! -e ${DEST_PATH}/${FILENAME} ]; then
	echo "The corresponding tarball is missing (${FILENAME})" >&2
	exit 1
fi

rm -rf tmp
mkdir tmp
tar xz -C tmp -f ${DEST_PATH}/${FILENAME}

if [ -e patches ]; then
  if [ -e patches/classic ]; then
    PATCH_DIR="../../patches/classic"
  else
    PATCH_DIR="../../patches"
  fi
  
  cd tmp/${SRC_DIR_PREFIX}${VER}
  ln -s ${PATCH_DIR} patches
  if [ -e patches/series ]; then
    quilt push -a
  fi
fi

echo "Done !"

