#!/usr/bin/python

__version__ = "$Revision$ $Date$"
__license__ = """
    Copyright (C) 2008  Proformatique

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License along
    with this program; if not, write to the Free Software Foundation, Inc.,
    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA..
"""

import sys
from xivo import agi_helpers
from xivo import xivo_helpers

agi = agi_helpers.agi_get_session()
cursor = xivo_helpers.db_connect().cursor()
number = sys.argv[1]

cursor.query("SELECT ${columns} FROM agentfeatures "
             "WHERE number = %s "
             "AND commented = 0",
             ('silent',),
             (number,))
res = cursor.fetchone()

if not res:
	agi_helpers.dp_break("Unknown agent number '%s'" % number)

options = ''

if res['silent']:
	options += 's'

agi.set_variable('XIVO_AGENTOPTIONS', options)
agi.verbose('AGI script "%s" successfully executed' % sys.argv[0])
