#!/usr/bin/python
#
# Authors : Sylvain Boily, Guillaume Knispel, Richard Braun
#	   Proformatique
#	   67, rue Voltaire
#	   92800 PUTEAUX
#	   (+33/0)1.41.38.99.60
#	   mailto:technique@proformatique.com
#	   (C) 2007 Proformatique

__version__ = "$Revision$ $Date$"
__license__ = """
    Copyright (C) 2007, Proformatique

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Lesser General Public
    License as published by the Free Software Foundation; either
    version 2.1 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public
    License along with this library; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
"""

CONFIG_FILE = '/etc/asterisk/xivo_agi.conf'

import xivo.to_path

import os
import sys
import time
import except_tb
import agi_helpers
import ConfigDict
from agi import *

agi = AGI()

#exten = s,n,Set(CHANTECH=${CUT(CHANNEL,/,1)})
#exten = s,n,System(echo "Channel: ${CHANTECH}/${REAL_EXTEN}" > ${FILE})
#exten = s,n,System(echo "MaxRetries: 2" >> ${FILE})
#exten = s,n,System(echo "RetryTime: 20" >> ${FILE})
#exten = s,n,System(echo "WaitTime: 20" >> ${FILE})
#exten = s,n,System(echo "Context: from-asterisk" >> ${FILE})
#exten = s,n,System(echo "Extension: ${CALLERID(num)}" >> ${FILE})
#exten = s,n,System(echo "Priority: 1" >> ${FILE})
#CallerID: "Cedric" <111>
#exten = s,n,System(chown asterisk:asterisk ${FILE})

srcnum = agi.get_variable('CALLERID(num)')
dstnum = agi.get_variable('REAL_DSTNUM')
channel = agi.get_variable('CHANNEL')
cb_passwd = agi.get_variable('CALLBACK_PASSWD')
cb_context = agi.get_variable('CALLBACK_CONTEXT')
chantech = channel.split('/')[0]

mtime = time.time() + 5
filename = "%s-%s.call" % (srcnum, int(mtime))

tmpfile = "/var/spool/asterisk/tmp/" + filename
realfile = "/var/spool/asterisk/outgoing/" + filename

file = open(tmpfile, 'w')
file.write("Channel: %s/%s\n"
           "MaxRetries: 0\n"
           "RetryTime: 30\n"
           "WaitTime: 30\n"
           "CallerID: %s\n"
           "Application: DISA\n"
           "Data: %s|%s\n" % (chantech, srcnum, srcnum, cb_passwd, cb_context))
file.close()

os.utime(tmpfile, (mtime, mtime))
os.rename(tmpfile, realfile)
agi.verbose('AGI script "%s" successfully executed' % sys.argv[0])
