#!/usr/bin/python

__version__ = "$Revision$ $Date$"
__license__ = """
    Copyright (C) 2007, 2008 Proformatique

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Lesser General Public
    License as published by the Free Software Foundation; either
    version 2.1 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public
    License along with this library; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
"""

CONFIG_FILE = '/etc/asterisk/xivo_agi.conf'

import xivo.to_path

import os
import sys
import time
from agi import *

agi = AGI()

srcnum = agi.get_variable('CALLERID(num)')
dstnum = agi.get_variable('REAL_DSTNUM')
channel = agi.get_variable('CHANNEL')
disa_params = sys.argv[1]
chantech = channel.split('/')[0]

mtime = time.time()
filename = "%s-%s.call" % (srcnum, int(mtime))

tmpfile = "/var/spool/asterisk/tmp/" + filename
realfile = "/var/spool/asterisk/outgoing/" + filename

file = open(tmpfile, 'w')
file.write("Channel: %s/%s\n"
           "MaxRetries: 0\n"
           "RetryTime: 30\n"
           "WaitTime: 30\n"
           "CallerID: %s\n"
           "Application: DISA\n"
           "Data: %s\n" % (chantech, srcnum, srcnum, disa_params))
file.close()

os.rename(tmpfile, realfile)
agi.verbose('AGI script "%s" successfully executed' % sys.argv[0])
