#!/usr/bin/python
#
# Authors : Sylvain Boily, Guillaume Knispel
#           Proformatique
#           67, rue Voltaire
#           92800 PUTEAUX
#           (+33/0)1.41.38.99.60
#           mailto:technique@proformatique.com
#           (C) 2007 Proformatique
#

__version__ = "$Revision$ $Date$"
__license__ = """
    Copyright (C) 2007, Proformatique

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Lesser General Public
    License as published by the Free Software Foundation; either
    version 2.1 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public
    License along with this library; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
"""

CONFIG_FILE = '/etc/asterisk/xivo_agi.conf'
CONFIG_LIB_PATH = 'py_lib_path'

import sys
from xivo import ConfigPath
from xivo.ConfigPath import *
ConfiguredPathHelper(CONFIG_FILE, CONFIG_LIB_PATH)
import anysql
from BackSQL import backsqlite
from BackSQL import backmysql
import ConfigParser
from ConfigDict import *

options = { "db_uri" : "" }
conf_obj = ConfigParser.ConfigParser()
conf_obj.readfp(open(CONFIG_FILE))
FillDictFromConfigSection(options, conf_obj, "db")

import string

try:
	exten = int(sys.argv[1])
except:
	print "VERBOSE \"Error no args found!\""
	sys.exit()

try:
	conn = anysql.connect_by_uri(options['db_uri'])
except:
	print "VERBOSE \"Error to connect %s\" %options['db_uri']"
	sys.exit()

cursor = conn.cursor()
query = "SELECT type,typeid,custom FROM didfeatures WHERE number=%d" % exten
cursor.execute(query)
t = cursor.fetchone()


if not t:
	print "VERBOSE \"No DID found !\""
	sys.exit()

type = t[0]
typeid = t[1]

if type == 'custom':
	(apps, args) = t.custom.split('(')
	(args, noargs) = args.split(')')
	args = string.replace(args,',','|')
	print "ANSWER"
	print "EXEC %s \"%s\"" %(apps, args)

if type == 'meetme':
	query = "SELECT number FROM meetmefeatures WHERE id=%d" % t[1]
	cursor.execute(query)
	m = cursor.fetchone()
	num = int(m[0])
	query = "SELECT context,number FROM extenumbers WHERE number=%d AND context!='did-extensions'" % num
	cursor.execute(query)
	g = cursor.fetchone()
	context = g[0]
	number = g[1]
	print "ANSWER"
	print "EXEC GOTO \"%s|%s|1\"" %(context,number)

if type == 'user':
	query = "SELECT number,context FROM userfeatures WHERE id=%d" % typeid
	cursor.execute(query)
	u = cursor.fetchone()
	number = u[0]
	context = u[1]
	num = int(number)
	query = "SELECT number,context FROM extenumbers WHERE number=%d AND context='%s'" %(num, context)
	cursor.execute(query)
	g = cursor.fetchone()
	number = g[0]
	context = g[1]
	print "ANSWER"
	print "EXEC GOTO \"%s|%s|1\"" %(context,number)

if type == 'group':
	query = "SELECT number,context FROM groupfeatures WHERE id=%d AND context!='did-extensions'" % typeid
	cursor.execute(query)
	g = cursor.fetchone()
	number = g[0]
	context = g[1]
	print "ANSWER"
	print "EXEC GOTO \"%s|%s|1\"" %(context,number)
