#!/usr/bin/python
#
# Authors : Sylvain Boily, Guillaume Knispel
#           Proformatique
#           67, rue Voltaire
#           92800 PUTEAUX
#           (+33/0)1.41.38.99.60
#           mailto:technique@proformatique.com
#           (C) 2007 Proformatique
#

__version__ = "$Revision: 616 $ $Date: 2007-05-16 11:48:13 +0200 (mer, 16 mai 2007) $"
__license__ = """
    Copyright (C) 2007, Proformatique

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Lesser General Public
    License as published by the Free Software Foundation; either
    version 2.1 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public
    License along with this library; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
"""

CONFIG_FILE = '/etc/asterisk/xivo_agi.conf'
CONFIG_LIB_PATH = 'py_lib_path'

import sys
from xivo import ConfigPath
from xivo.ConfigPath import *

try:
        InsertPathListSys(SortedValuesFromConfigSection(CONFIG_FILE, CONFIG_LIB_PATH))
except NoSectionError, s:
        print >> sys.stderr, "WARNING: Section [%s] apparently missing from configuration file %s" % (CONFIG_LIB_PATH, CONFIG_FILE)

import anysql
from BackSQL import backsqlite
from BackSQL import backmysql
import ConfigParser
from ConfigDict import *

options = { "db_uri" : "" }
conf_obj = ConfigParser.ConfigParser()
conf_obj.readfp(open(CONFIG_FILE))
FillDictFromConfigSection(options, conf_obj, "db")

import string, re, os, datetime

if len(sys.argv) != 4:
	print "VERBOSE \"Missing arguments\""
	sys.exit()

if sys.argv[1].isdigit():
	callexten = sys.argv[1]
else:
	print "VERBOSE \"Error it's not a phone number!\""
	sys.exit()

file = sys.argv[2]
filepdf = string.replace(file,".tif",".pdf")

if sys.argv[3].isdigit():
	mailbox = sys.argv[3]
else:
	print "VERBOSE \"Error it's not a phone number!\""

try:
        conn = anysql.connect_by_uri(options['db_uri'])
except:
        print "VERBOSE \"Error to connect %s\" %options['db_uri']"
        sys.exit()

query = "SELECT email, fullname FROM uservoicemail WHERE mailbox=%d" % int(mailbox)
cursor = conn.cursor()
cursor.execute(query)
r = cursor.fetchone()

if not r:
	print "VERBOSE \"Sorry there is not user for this FAX\""
	sys.exit()

mail = r[0]
name = r[1]
date = datetime.datetime.now()

if not mail and not name:
	print "VERBOSE \"Sorry there is no person at this number\""
	print "VERBOSE \"Missing mail or name\""
	sys.exit()
else:
	try:
		if os.stat(file).st_size != 0:
			print "VERBOSE \"Convert tif to pdf\""
			os.system("/usr/bin/tiff2pdf -o %s %s" %(filepdf, file))
			print "VERBOSE \"Send FAX to %s (%s) at %s\"" %(mail, name, date)
			os.system("echo \"Bonjour %s,\n\nVous avez recu un FAX , il est joint dans ce mail !\n\nCordialement,\nService IPBX\" | /usr/bin/mutt -s \"Reception FAX de %s\" -a %s %s" %(name, callexten, filepdf, mail))
			try:
				os.remove(filepdf)
				os.remove(file)
			except OSError:
				print "VERBOSE \"Error there is no file to remove\""
				sys.exit()
		else:
			print "VERBOSE \"Sorry the file is empty\""
			try:
				os.remove(file)
			except OSError:
				print "VERBOSE \"Error there is no file to remove\""
				sys.exit()
	except OSError:
		print "VERBOSE \"Sorry there is no fax receive\""
		sys.exit()
