#!/usr/bin/python
#

__version__ = "$Revision$ $Date$"
__license__ = """
    Copyright (C) 2007, 2008 Proformatique

    This software is free software; you can redistribute it and/or
    modify it under the terms of the GNU Lesser General Public
    License as published by the Free Software Foundation; either
    version 2.1 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public
    License along with this library; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
"""

import xivo.to_path

import os
import sys
import agi_helpers
from agi import *

agi = AGI()

def atexit(filename, filepdf):
	try:
		os.remove(filename)
		os.remove(filepdf)

	except OSError:
		pass
def exit_on_error(filename, filepdf, message):
	atexit(filename, filepdf)
	agi_helpers.dp_break(agi, message)

filename = sys.argv[1]
filepdf = filename.replace(".tif",".pdf")

email = sys.argv[2]

dstnum = agi.get_variable('REAL_DSTNUM')

status = os.system("/usr/bin/tiff2pdf -o '%s' '%s'" % (filepdf, filename))

if status:
	exit_on_error(filename, filepdf, "Unable to convert fax to PDF")

status = os.system("echo \"Un nouveau fax est arrive. Il est joint dans ce mail.\n\nCordialement,\nService IPBX\" | /usr/bin/mutt -s \"Reception de FAX vers %s\" -a %s %s" % (dstnum, filepdf, email))

if status:
	exit_on_error(filename, filepdf, "Unable to send fax as an email")

atexit(filename, filepdf)
agi.verbose('AGI script "%s" successfully executed' % sys.argv[0])
