#!/usr/bin/python
#
# Authors : Sylvain Boily, Guillaume Knispel
#           Proformatique
#           67, rue Voltaire
#           92800 PUTEAUX
#           (+33/0)1.41.38.99.60
#           mailto:technique@proformatique.com
#           (C) 2007 Proformatique
#

__version__ = "$Revision$ $Date$"
__license__ = """
    Copyright (C) 2007, Proformatique

    This software is free software; you can redistribute it and/or
    modify it under the terms of the GNU Lesser General Public
    License as published by the Free Software Foundation; either
    version 2.1 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public
    License along with this library; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
"""

CONFIG_FILE = '/etc/asterisk/xivo_agi.conf'
CONFIG_LIB_PATH = 'py_lib_path'

import sys, string
from xivo import ConfigPath
from xivo.ConfigPath import *
ConfiguredPathHelper(CONFIG_FILE, CONFIG_LIB_PATH)
import ConfigParser
from ConfigDict import *
from agi import *

agi = AGI()

if len(sys.argv) > 1:
	if sys.argv[1].isdigit():
		exten = sys.argv[1]
else:
	agi.verbose("Sorry there is not number !")
	sys.exit()

ring = "/etc/asterisk/xivo_ring.conf"

config = ConfigParser.ConfigParser()
config.readfp(open(ring))

phonetype = config.get('number', exten)

if not phonetype:
	agi.verbose("Sorry there is no phonetype !")
	sys.exit()

agi.set_variable("RINGINTERNAL", config.get(phonetype, 'intern'))
agi.set_variable("RINGEXTERNAL", config.get(phonetype, 'extern'))
agi.set_variable("RINGGROUP", config.get(phonetype, 'group'))

if phonetype == 'thomson':
	agi.set_variable("ISTHOMSON", "1")
