#!/usr/bin/python
#
# Authors : Sylvain Boily, Guillaume Knispel
#           Proformatique
#           67, rue Voltaire
#           92800 PUTEAUX
#           (+33/0)1.41.38.99.60
#           mailto:technique@proformatique.com
#           (C) 2007 Proformatique
#

__version__ = "$Revision$ $Date$"
__license__ = """
    Copyright (C) 2007, Proformatique

    This software is free software; you can redistribute it and/or
    modify it under the terms of the GNU Lesser General Public
    License as published by the Free Software Foundation; either
    version 2.1 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public
    License along with this library; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
"""

import xivo.to_path

import sys
import ConfigParser
from ConfigDict import *
from agi import *

ring = "/etc/asterisk/xivo_ring.conf"

parser = ConfigParser.RawConfigParser()
parser.readfp(open(ring))

agi = AGI()

srcnum = agi.get_variable('REAL_SRCNUM')
dstnum = agi.get_variable('REAL_DSTNUM')
context = agi.get_variable('REAL_CONTEXT')
calltype = agi.get_variable('REAL_CALLTYPE')

try:
	phonetype = parser.get('number', "%s@%s" % (dstnum, context))
except ConfigParser.NoOptionError:
	agi.verbose("Using the phone ring tone")
	sys.exit()

ringtype = parser.get(phonetype, calltype)
agi.set_variable('XIVO_RINGTYPE', ringtype)
agi.verbose("Using ring tone %s" % ringtype)

if phonetype == 'thomson':
	agi.set_variable("ISTHOMSON", "1")
