#!/usr/bin/python
#
# Authors : Sylvain Boily, Guillaume Knispel
#           Proformatique
#           67, rue Voltaire
#           92800 PUTEAUX
#           (+33/0)1.41.38.99.60
#           mailto:technique@proformatique.com
#           (C) 2007 Proformatique
#

__version__ = "$Revision$ $Date$"
__license__ = """
    Copyright (C) 2007, Proformatique

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Lesser General Public
    License as published by the Free Software Foundation; either
    version 2.1 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public
    License along with this library; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
"""

CONFIG_FILE = '/etc/asterisk/xivo_agi.conf'
CONFIG_LIB_PATH = 'py_lib_path'

import sys
from xivo import ConfigPath
from xivo.ConfigPath import *
ConfiguredPathHelper(CONFIG_FILE, CONFIG_LIB_PATH)
import anysql
from BackSQL import backsqlite
from BackSQL import backmysql
import ConfigParser
from ConfigDict import *
from xivo import agi

options = { "db_uri" : "" }
conf_obj = ConfigParser.ConfigParser()
conf_obj.readfp(open(CONFIG_FILE))
FillDictFromConfigSection(options, conf_obj, "db")


if len(sys.argv) != 2:
	agi.agi_verbose("Error no args found!")
        sys.exit()

# XXX TODO BUGBUG FIXME SATAN: the following lines make absolutely sense to me (Xilun - 2007-06-15)
# XXX For me too :-) (Quintana - 2007-07-03)
try:
        exten = sys.argv[1]
	query = "SELECT groupfeatures.name,groupfeatures.number,queue.timeout FROM groupfeatures,queue WHERE groupfeatures.name=queue.name AND groupfeatures.number='%s';" % exten
except:
	exten = sys.argv[1]
	query = "SELECT groupfeatures.name,groupfeatures.number,queue.timeout FROM groupfeatures,queue WHERE groupfeatures.name=queue.name AND groupfeatures.name='%s';" % exten

try:
        conn = anysql.connect_by_uri(options['db_uri'])
except:
        agi.agi_verbose("Unable to connect to %s" %options['db_uri'])
        raise

cursor = conn.cursor()
cursor.execute(query)
r = cursor.fetchone()

if not r:
	agi.agi_verbose("No ring group found")
	sys.exit()

name = r[0]
number = r[1]
timeout = r[2]

if name and number and timeout:
	agi.agi_set_variable("GEXT", "%s" % number)
	agi.agi_set_variable("GNAME", "%s" % name)
	agi.agi_set_variable("GTIMEOUT", "%s" % timeout)
else:
	agi.agi_verbose("There is an error")
