#!/usr/bin/python
#
# Authors : Sylvain Boily, Guillaume Knispel
#           Proformatique
#           67, rue Voltaire
#           92800 PUTEAUX
#           (+33/0)1.41.38.99.60
#           mailto:technique@proformatique.com
#           (C) 2007 Proformatique
#

__version__ = "$Revision$ $Date$"
__license__ = """
    Copyright (C) 2007, Proformatique

    This software is free software; you can redistribute it and/or
    modify it under the terms of the GNU Lesser General Public
    License as published by the Free Software Foundation; either
    version 2.1 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public
    License along with this library; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
"""

CONFIG_FILE = '/etc/asterisk/xivo_agi.conf'

import xivo.to_path

import sys
import anysql
from BackSQL import backsqlite
from BackSQL import backmysql
import ConfigParser
from ConfigDict import *
from agi import *

options = { "db_uri" : "" }
conf_obj = ConfigParser.ConfigParser()
conf_obj.readfp(open(CONFIG_FILE))
FillDictFromConfigSection(options, conf_obj, "db")

agi = AGI()

if len(sys.argv) != 2:
	agi.verbose("Error no args found!")
        sys.exit()

exten = sys.argv[1]

# If is a call group search to groupfeatures.number
# If is a call user and search a group for this user search to groupfeatures.name
if exten.isdigit():
	query = "SELECT groupfeatures.name,groupfeatures.number,queue.timeout FROM groupfeatures,queue \
			WHERE groupfeatures.name=queue.name AND groupfeatures.number='%s';" % exten
else:
	query = "SELECT groupfeatures.name,groupfeatures.number,queue.timeout FROM groupfeatures,queue \
			WHERE groupfeatures.name=queue.name AND groupfeatures.name='%s';" % exten


try:
        conn = anysql.connect_by_uri(options['db_uri'])
except:
        agi.verbose("Unable to connect to %s" %options['db_uri'])
        raise

cursor = conn.cursor()
cursor.execute(query)
r = cursor.fetchone()

if not r:
	agi.verbose("No ring group found")
	sys.exit()

name = r[0]
number = r[1]
timeout = r[2]

if name and number and timeout:
	agi.set_variable("GEXT", "%s" % number)
	agi.set_variable("GNAME", "%s" % name)
	agi.set_variable("GTIMEOUT", "%s" % timeout)
else:
	agi.verbose("There is an error")
