#!/usr/bin/python

__version__ = "$Revision$ $Date$"
__license__ = """
    Copyright (C) 2007, 2008  Proformatique

    This program is free software; you can redistribute it and/or
    modify it under the terms of the GNU General Public License
    version 2 as published by the Free Software Foundation.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301, USA
"""

CONFIG_FILE = '/etc/asterisk/xivo_agi.conf'

import xivo.to_path

import sys
import anysql
import agi_helpers
from BackSQL import backsqlite
from BackSQL import backmysql
import ConfigDict
from agi import *
import agitb

agi = AGI()
agitb.enable(agi)
db_uri = ConfigDict.ReadSingleKey(CONFIG_FILE, 'db', 'db_uri')

# Cursors have a weak reference on their connection, so make a strong one.
conn = agi_helpers.db_connect(agi, db_uri)
cursor = conn.cursor()
exten_pattern = agi.get_variable('REAL_EXTENPATTERN')

cursor.query("SELECT ${columns} FROM incall "
             "WHERE exten = %s "
             "AND linked = 1 "
             "AND commented = 0",
             ('type', 'typeval', 'applicationval'),
             (exten_pattern,))
res = cursor.fetchone()

if not res:
	agi_helpers.dp_break(agi, "Unknown extension '%s'" % exten_pattern)

agi_helpers.set_fwd_vars(agi, cursor, res['type'], res['typeval'], res['applicationval'], "XIVO_DIDTYPE", "XIVO_DIDTYPEVAL1", "XIVO_DIDTYPEVAL2")
agi.verbose('AGI script "%s" successfully executed' % sys.argv[0])
