#!/usr/bin/python
#
# Authors : Sylvain Boily, Guillaume Knispel
#           Proformatique
#           67, rue Voltaire
#           92800 PUTEAUX
#           (+33/0)1.41.38.99.60
#           mailto:technique@proformatique.com
#           (C) 2007 Proformatique
#

__version__ = "$Revision: 616 $ $Date: 2007-05-16 11:48:13 +0200 (mer, 16 mai 2007) $"
__license__ = """
    Copyright (C) 2007, Proformatique

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Lesser General Public
    License as published by the Free Software Foundation; either
    version 2.1 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public
    License along with this library; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
"""

CONFIG_FILE = '/etc/asterisk/xivo_agi.conf'
CONFIG_LIB_PATH = 'py_lib_path'

import sys
from xivo import ConfigPath
from xivo.ConfigPath import *
ConfiguredPathHelper(CONFIG_FILE, CONFIG_LIB_PATH)
import anysql
from BackSQL import backsqlite
from BackSQL import backmysql
import ConfigParser
from ConfigDict import *

options = { "db_uri" : "" }
conf_obj = ConfigParser.ConfigParser()
conf_obj.readfp(open(CONFIG_FILE))
FillDictFromConfigSection(options, conf_obj, "db")

try:
        exten = int(sys.argv[1])
except:
        print "VERBOSE \"Error no args found!\""
        sys.exit()

try:
        conn = anysql.connect_by_uri(options['db_uri'])
except:
        print "VERBOSE \"Error to connect %s\" %options['db_uri']"
        sys.exit()

cursor = conn.cursor()
query = "SELECT mode,musiconhold,exit,quiet,record,video FROM meetmefeatures WHERE number='%s'" %exten
cursor.execute(query)
r = cursor.fetchone()

if not r:
        print "VERBOSE \"No meetme found\""
        sys.exit()

mode = r[0]
musiconhold = r[1]
exit = r[2]
quiet = r[3]
record = r[4]
video = r[5]

options = ''

try:
        if mode == 'all':
                options = ''
        if mode == 'talk':
                options = 't'
        if mode == 'listen':
                options = 'm'
        if musiconhold:
                options = options + 'M(' + musiconhold + ')'
        if exit:
                options = options + 'p'
        if quiet:
                options = options + 'q'
        if record:
                options = options + 'r'
        if video:
                pass
        options = options + 's'

        print "SET VARIABLE MEETMEOPTIONS \"" + options + "\""
except:
        pass
