#!/usr/bin/python
#
# Authors : Sylvain Boily, Guillaume Knispel
#           Proformatique
#           67, rue Voltaire
#           92800 PUTEAUX
#           (+33/0)1.41.38.99.60
#           mailto:technique@proformatique.com
#           (C) 2007 Proformatique
#

__version__ = "$Revision: 616 $ $Date: 2007-05-16 11:48:13 +0200 (mer, 16 mai 2007) $"
__license__ = """
    Copyright (C) 2007, Proformatique

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Lesser General Public
    License as published by the Free Software Foundation; either
    version 2.1 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public
    License along with this library; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
"""


import ConfigParser, string, sys

try:
        exten = sys.argv[1]
except:
        exten = ""

outcall = "/etc/asterisk/xivo_outcall.conf"

config = ConfigParser.ConfigParser()
config.readfp(open(outcall))

sys.stdout.write("SET VARIABLE USEENUM \"" + config.get('outcall', 'useenum') + "\"\n")
sys.stdout.write("SET VARIABLE USEZEROFOROUT \"" + config.get('outcall', 'usezeroforout') + "\"\n")
sys.stdout.write("SET VARIABLE SETCALLERID \"" + config.get('outcall', 'setcallerid') + "\"\n")
sys.stdout.write("SET VARIABLE CHANVOIP \"" + config.get('outcall', 'chanvoip') + "\"\n")
sys.stdout.write("SET VARIABLE CHANISDN \"" + config.get('outcall', 'chanisdn') + "\"\n")
sys.stdout.write("SET VARIABLE EMERGENCYNUMBERS \"" + config.get('outcall', 'emergencynumbers') + "\"\n")
sys.stdout.write("SET VARIABLE EXTERNNUM \"" + config.get('outcall', 'externnum') + "\"\n")
sys.stdout.write("SET VARIABLE USEVOIPFORCALL \"" + config.get('outcall', 'usevoipforcall') + "\"\n")
