#!/usr/bin/python
#
# Authors : Sylvain Boily, Guillaume Knispel
#           Proformatique
#           67, rue Voltaire
#           92800 PUTEAUX
#           (+33/0)1.41.38.99.60
#           mailto:technique@proformatique.com
#           (C) 2007 Proformatique
#

__version__ = "$Revision$ $Date$"
__license__ = """
    Copyright (C) 2007, Proformatique

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Lesser General Public
    License as published by the Free Software Foundation; either
    version 2.1 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public
    License along with this library; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
"""

import xivo.to_path

import sys

import ConfigParser, telnetlib
from agi import *

# This is the configuration file, please do not change the path because if was editable by xivo web interface
mobileagent = "/etc/asterisk/xivo_mobile_agent.conf"
DEBUG = 1
USER = 'admin'
PASSWORD = 'superpass'

def print_verbose(txt):
        if DEBUG:
                sys.stdout.write("VERBOSE \"%s\"\n" % agi_escape_string(txt))
                sys.stdout.flush()

try:
	config = ConfigParser.ConfigParser()
	config.readfp(open(mobileagent))
except IOError:
	print_verbose("Configuration file not found : %s" % mobileagent)
	raise

# FIXME: action_thomson has nothing to do here
def action_thomson(ip, cmd_telnet):
        tn = telnetlib.Telnet(ip)

        tn.read_until("Login: ")
        tn.write(USER + "\r\n")
        if PASSWORD:
                tn.read_until("Password: ")
                tn.write(PASSWORD + "\r\n")

        for cmd in cmd_telnet:
                print_verbose("running telnet command: " + cmd)
                tn.read_until("["+USER+"]#")
                tn.write("%s\n" % cmd)
                if cmd == 'reboot':
                        break
        tn.close()


# This function returns all informations relatives to a specific agent
def get_agent(agent):
	if config.has_section(agent):
		# <XXX TODO BUGBUG FIXME SATAN>
		sys.stdout.write("SET VARIABLE ISMOBILEAGENT \"" + config.get(agent, 'isagent') + "\"\n")
		sys.stdout.write("SET VARIABLE CALLUSERANDAGENT \"" + config.get(agent, 'calluserandagent') + "\"\n")
		sys.stdout.write("SET VARIABLE SECRET \"" + config.get(agent, 'secret') + "\"\n")
		sys.stdout.write("SET VARIABLE CONTEXT_ \"" + config.get(agent, 'context') + "\"\n")
		# </XXX TODO BUGBUG FIXME SATAN>

if len(sys.argv) > 1:
	if sys.argv[1].isdigit():
		get_agent(sys.argv[1])
		ip = '192.168.0.199'   # I'm anxious (Xilun - 2007-06-15)
		name = 'Sylvain Boily' # I'm afraid (Xilun - 2007-06-15)
		#action_thomson(ip, ('sip set tel_name 1 ' + name, 'logout'))  # now I'm really really really frightened (Xilun - 2007-06-15)
