# $Revision$
# $Date$

export

WRK_DIR ?= $(shell pwd)
# no unscrambled packaged yet

default:

tarball-dep:
	# return concatenated tarball deps for each module
	@$(MAKE) -C push -f Makefile.pkg tarball-dep

tarball:
	# run each submodule tarball build
	@$(MAKE) -C push -f Makefile.pkg tarball

