# $Revision$
# $Date$

export

WRK_DIR ?= $(shell pwd)
# no unscrambled packaged yet
DEB_TB_SCRAMBLED = "0"

default:

tarball-scrambled:
	@echo "$(DEB_TB_SCRAMBLED)"

tarball:
	# run each submodule tarball build
	@$(MAKE) -C push -f Makefile.pkg tarball

