<?php

#
# XiVO Web-Interface
# Copyright (C) 2006-2010  Proformatique <technique@proformatique.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

$array = array();
$array['AD'] = array(
	'default' => 'ca_AD',
	'locale' => array('ca_AD' => 1),
	'tz' => array('Europe/Andorra' => 1));

$array['AE'] = array(
	'default' => 'ar_AE',
	'locale' => array('ar_AE' => 1),
	'tz' => array('Asia/Dubai' => 1));

$array['AL'] = array(
	'default' => 'sq_AL',
	'locale' => array('sq_AL' => 1),
	'tz' => array('Europe/Tirane' => 1));

$array['AM'] = array(
	'default' => 'hy_AM',
	'locale' => array('hy_AM' => 1),
	'tz' => array('Asia/Yerevan' => 1));

$array['AO'] = array(
	'default' => 'pt_AO',
	'locale' => array('pt_AO' => 1),
	'tz' => array('Africa/Luanda' => 1));

$array['AR'] = array(
	'default' => 'es_AR',
	'locale' => array('es_AR' => 1),
	'tz' => array(
		'America/Argentina/Buenos_Aires' => 1,
		'America/Argentina/Catamarca' => 1,
		'America/Argentina/Cordoba' => 1,
		'America/Argentina/Jujuy' => 1,
		'America/Argentina/La_Rioja' => 1,
		'America/Argentina/Mendoza' => 1,
		'America/Argentina/Rio_Gallegos' => 1,
		'America/Argentina/San_Juan' => 1,
		'America/Argentina/Tucuman' => 1,
		'America/Argentina/Ushuaia' => 1));

$array['AT'] = array(
	'default' => 'de_AT',
	'locale' => array('de_AT' => 1),
	'tz' => array('Europe/Vienna' => 1));

$array['AU'] = array(
	'default' => 'en_AU',
	'locale' => array('en_AU' => 1),
	'tz' => array(
		'Antarctica/Casey' => 1,
		'Antarctica/Davis' => 1,
		'Antarctica/Mawson' => 1,
		'Australia/Adelaide' => 1,
		'Australia/Brisbane' => 1,
		'Australia/Broken_Hill' => 1,
		'Australia/Currie' => 1,
		'Australia/Darwin' => 1,
		'Australia/Eucla' => 1,
		'Australia/Hobart' => 1,
		'Australia/Lindeman' => 1,
		'Australia/Lord_Howe' => 1,
		'Australia/Melbourne' => 1,
		'Australia/Perth' => 1,
		'Australia/Sydney' => 1));

$array['AZ'] = array(
	'default' => 'az_AZ',
	'locale' => array('az_AZ' => 1),
	'tz' => array('Asia/Baku' => 1));

$array['BA'] = array(
	'default' => 'bs_BA',
	'locale' => array('bs_BA' => 1));

$array['BD'] = array(
	'default' => 'bn_BD',
	'locale' => array('bn_BD' => 1),
	'tz' => array('Asia/Dhaka' => 1));

$array['BE'] = array(
	'locale' => array(
		'de_BE' => 1,
		'fr_BE' => 1,
		'nl_BE' => 1,
		'wa_BE' => 1),
	'tz' => array('Europe/Brussels' => 1));

$array['BF'] = array(
	'default' => 'fr_BF',
	'locale' => array(
		'fr_BF' => 1,
		'dyu_BF' => 1,
		'ff_BF' => 1),
	'tz' => array('Africa/Ouagadougou' => 1));

$array['BG'] = array(
	'default' => 'bg_BG',
	'locale' => array('bg_BG' => 1),
	'tz' => array('Europe/Sofia' => 1));

$array['BH'] = array(
	'default' => 'ar_BH',
	'locale' => array('ar_BH' => 1),
	'tz' => array('Asia/Bahrain' => 1));

$array['BI'] = array(
	'default' => 'fr_BI',
	'locale' => array(
		'fr_BI' => 1,
		'rn_BI' => 1),
	'tz' => array('Africa/Bujumbura' => 1));

$array['BJ'] = array(
	'default' => 'fr_BJ',
	'locale' => array('fr_BJ' => 1),
	'tz' => array('Africa/Porto-Novo' => 1));

$array['BO'] = array(
	'default' => 'es_BO',
	'locale' => array('es_BO' => 1),
	'tz' => array('America/La_Paz' => 1));

$array['BR'] = array(
	'default' => 'pt_BR',
	'locale' => array('pt_BR' => 1),
	'tz' => array(
		'America/Araguaina' => 1,
		'America/Bahia' => 1,
		'America/Belem' => 1,
		'America/Boa_Vista' => 1,
		'America/Campo_Grande' => 1,
		'America/Cuiaba' => 1,
		'America/Eirunepe' => 1,
		'America/Fortaleza' => 1,
		'America/Maceio' => 1,
		'America/Manaus' => 1,
		'America/Noronha' => 1,
		'America/Porto_Velho' => 1,
		'America/Recife' => 1,
		'America/Rio_Branco' => 1,
		'America/Sao_Paulo' => 1));

$array['BT'] = array(
	'default' => 'dz_BT',
	'locale' => array('dz_BT' => 1),
	'tz' => array('Asia/Thimphu' => 1));

$array['BW'] = array(
	'default' => 'en_BW',
	'locale' => array('en_BW' => 1),
	'tz' => array('Africa/Gaborone' => 1));

$array['BY'] = array(
	'default' => 'be_BY',
	'locale' => array('be_BY' => 1),
	'tz' => array('Europe/Minsk' => 1));

$array['CA'] = array(
	'locale' => array(
		'en_CA' => 1,
		'fr_CA' => 1),
	'tz' => array(
		'America/Atikokan' => 1,
		'America/Blanc-Sablon' => 1,
		'America/Cambridge_Bay' => 1,
		'America/Dawson' => 1,
		'America/Dawson_Creek' => 1,
		'America/Edmonton' => 1,
		'America/Glace_Bay' => 1,
		'America/Goose_Bay' => 1,
		'America/Halifax' => 1,
		'America/Inuvik' => 1,
		'America/Iqaluit' => 1,
		'America/Moncton' => 1,
		'America/Montreal' => 1,
		'America/Nipigon' => 1,
		'America/Pangnirtung' => 1,
		'America/Rainy_River' => 1,
		'America/Rankin_Inlet' => 1,
		'America/Regina' => 1,
		'America/St_Johns' => 1,
		'America/Swift_Current' => 1,
		'America/Thunder_Bay' => 1,
		'America/Toronto' => 1,
		'America/Vancouver' => 1,
		'America/Whitehorse' => 1,
		'America/Winnipeg' => 1,
		'America/Yellowknife' => 1));

$array['CD'] = array(
	'default' => 'fr_CD',
	'locale' => array(
		'fr_CD' => 1,
		'kg_CD' => 1,
		'ln_CD' => 1,
		'sw_CD' => 1,
		'lua_CD' => 1),
	'tz' => array(
		'Africa/Kinshasa' => 1,
		'Africa/Lubumbashi' => 1));

$array['CF'] = array(
	'default' => 'sg_CF',
	'locale' => array(
		'sg_CF' => 1,
		'fr_CF' => 1),
	'tz' => array('Africa/Bangui' => 1));

$array['CG'] = array(
	'default' => 'fr_CG',
	'locale' => array(
		'fr_CG' => 1,
		'kg_CG' => 1,
		'ln_CG' => 1),
	'tz' => array('Africa/Brazzaville' => 1));

$array['CH'] = array(
	'locale' => array(
		'de_CH' => 1,
		'fr_CH' => 1,
		'it_CH' => 1),
	'tz' => array('Europe/Zurich' => 1));

$array['CI'] = array(
	'default' => 'fr_CI',
	'locale' => array(
		'fr_CI' => 1,
		'dyu_CI' => 1),
	'tz' => array('Africa/Abidjan' => 1));

$array['CL'] = array(
	'default' => 'es_CL',
	'locale' => array('es_CL' => 1),
	'tz' => array(
		'America/Santiago' => 1,
		'Pacific/Easter' => 1));

$array['CM'] = array(
	'default' => 'fr_CM',
	'locale' => array(
		'fr_CM' => 1,
		'en_CM' => 1,
		'ff_CM' => 1),
	'tz' => array('Africa/Douala' => 1));

$array['CN'] = array(
	'default' => 'zh_CN',
	'locale' => array('zh_CN' => 1),
	'tz' => array(
		'Asia/Chongqing' => 1,
		'Asia/Harbin' => 1,
		'Asia/Kashgar' => 1,
		'Asia/Shanghai' => 1,
		'Asia/Urumqi' => 1));

$array['CO'] = array(
	'default' => 'es_CO',
	'locale' => array('es_CO' => 1),
	'tz' => array('America/Bogota' => 1));

$array['CR'] = array(
	'default' => 'es_CR',
	'locale' => array('es_CR' => 1),
	'tz' => array('America/Costa_Rica' => 1));

$array['CS'] = array(
	'default' => 'sr_CS',
	'locale' => array('sr_CS' => 1));

$array['CY'] = array(
	'locale' => array(
		'el_CY' => 1,
		'tr_CY' => 1),
	'tz' => array('Asia/Nicosia' => 1));

$array['CZ'] = array(
	'default' => 'cs_CZ',
	'locale' => array('cs_CZ' => 1),
	'tz' => array('Europe/Prague' => 1));

$array['DE'] = array(
	'default' => 'de_DE',
	'locale' => array(
		'de_DE' => 1,
		'hsb_DE' => 1),
	'tz' => array('Europe/Berlin' => 1));

$array['DJ'] = array(
	'locale' => array(
		'aa_DJ' => 1,
		'so_DJ' => 1),
	'tz' => array('Africa/Djibouti' => 1));

$array['DK'] = array(
	'locale' => array(
		'da_DK' => 1,
		'en_DK' => 1),
	'tz' => array('Europe/Copenhagen' => 1));

$array['DO'] = array(
	'default' => 'es_DO',
	'locale' => array('es_DO' => 1),
	'tz' => array('America/Santo_Domingo' => 1));

$array['DZ'] = array(
	'default' => 'ar_DZ',
	'locale' => array('ar_DZ' => 1),
	'tz' => array('Africa/Algiers' => 1));

$array['EC'] = array(
	'default' => 'es_EC',
	'locale' => array('es_EC' => 1),
	'tz' => array(
		'America/Guayaquil' => 1,
		'Pacific/Galapagos' => 1));

$array['EE'] = array(
	'default' => 'et_EE',
	'locale' => array('et_EE' => 1),
	'tz' => array('Europe/Tallinn' => 1));

$array['EG'] = array(
	'default' => 'ar_EG',
	'locale' => array('ar_EG' => 1),
	'tz' => array('Africa/Cairo' => 1));

$array['ER'] = array(
	'locale' => array(
		'aa_ER' => 1,
		'byn_ER' => 1,
		'gez_ER' => 1,
		'ti_ER' => 1,
		'tig_ER' => 1),
	'tz' => array('Africa/Asmara' => 1));

$array['ES'] = array(
	'default' => 'es_ES',
	'locale' => array(
		'an_ES' => 1,
		'ast_ES' => 1,
		'ca_ES' => 1,
		'es_ES' => 1,
		'eu_ES' => 1,
		'gl_ES' => 1),
	'tz' => array(
		'Africa/Ceuta' => 1,
		'Atlantic/Canary' => 1,
		'Europe/Madrid' => 1));

$array['ET'] = array(
	'locale' => array(
		'aa_ET' => 1,
		'am_ET' => 1,
		'gez_ET' => 1,
		'om_ET' => 1,
		'sid_ET' => 1,
		'so_ET' => 1,
		'ti_ET' => 1,
		'wal_ET' => 1),
	'tz' => array('Africa/Addis_Ababa' => 1));

$array['FI'] = array(
	'default' => 'fi_FI',
	'locale' => array(
		'fi_FI' => 1,
		'sv_FI' => 1),
	'tz' => array('Europe/Helsinki' => 1));

$array['FO'] = array(
	'default' => 'fo_FO',
	'locale' => array('fo_FO' => 1),
	'tz' => array('Atlantic/Faroe' => 1));

$array['FR'] = array(
	'default' => 'fr_FR',
	'locale' => array(
		'br_FR' => 1,
		'ca_FR' => 1,
		'fr_FR' => 1,
		'oc_FR' => 1),
	'tz' => array(
		'Antarctica/DumontDUrville' => 1,
		'Europe/Paris' => 1));

$array['GA'] = array(
	'default' => 'fr_GA',
	'locale' => array('fr_GA' => 1),
	'tz' => array('Africa/Libreville' => 1));

$array['GB'] = array(
	'default' => 'en_GB',
	'locale' => array(
		'cy_GB' => 1,
		'en_GB' => 1,
		'gd_GB' => 1,
		'gv_GB' => 1,
		'kw_GB' => 1),
	'tz' => array(
		'Antarctica/Rothera' => 1,
		'Europe/London' => 1));

$array['GE'] = array(
	'default' => 'ka_GE',
	'locale' => array('ka_GE' => 1),
	'tz' => array('Asia/Tbilisi' => 1));

$array['GH'] = array(
	'default' => 'en_GH',
	'locale' => array(
		'en_GH' => 1,
		'ak_GH' => 1,
		'ha_GH' => 1),
	'tz' => array('Africa/Accra' => 1));

$array['GL'] = array(
	'default' => 'kl_GL',
	'locale' => array('kl_GL' => 1),
	'tz' => array(
		'America/Danmarkshavn' => 1,
		'America/Godthab' => 1,
		'America/Scoresbysund' => 1,
		'America/Thule' => 1));

$array['GM'] = array(
	'default' => 'en_GM',
	'locale' => array(
		'en_GM' => 1,
		'man_GM' => 1,
		'wo_GM' => 1),
	'tz' => array('Africa/Banjul' => 1));

$array['GN'] = array(
	'default' => 'fr_GN',
	'locale' => array(
		'fr_GN' => 1,
		'ff_GN' => 1),
	'tz' => array('Africa/Conakry' => 1));

$array['GQ'] = array(
	'default' => 'es_GQ',
	'locale' => array(
		'es_GQ' => 1,
		'fr_GQ' => 1),
	'tz' => array('Africa/Malabo' => 1));

$array['GR'] = array(
	'default' => 'el_GR',
	'locale' => array('el_GR' => 1),
	'tz' => array('Europe/Athens' => 1));

$array['GT'] = array(
	'default' => 'es_GT',
	'locale' => array('es_GT' => 1),
	'tz' => array('America/Guatemala' => 1));

$array['GW'] = array(
	'default' => 'pt_GW',
	'locale' => array('pt_GW' => 1),
	'tz' => array('Africa/Bissau' => 1));

$array['HK'] = array(
	'locale' => array(
		'en_HK' => 1,
		'zh_HK' => 1),
	'tz' => array('Asia/Hong_Kong' => 1));

$array['HN'] = array(
	'default' => 'es_HN',
	'locale' => array('es_HN' => 1),
	'tz' => array('America/Tegucigalpa' => 1));

$array['HR'] = array(
	'default' => 'hr_HR',
	'locale' => array('hr_HR' => 1),
	'tz' => array('Europe/Zagreb' => 1));

$array['HU'] = array(
	'default' => 'hu_HU',
	'locale' => array('hu_HU' => 1),
	'tz' => array('Europe/Budapest' => 1));

$array['ID'] = array(
	'default' => 'id_ID',
	'locale' => array('id_ID' => 1),
	'tz' => array(
		'Asia/Jakarta' => 1,
		'Asia/Jayapura' => 1,
		'Asia/Makassar' => 1,
		'Asia/Pontianak' => 1));

$array['IE'] = array(
	'locale' => array(
		'en_IE' => 1,
		'ga_IE' => 1),
	'tz' => array('Europe/Dublin' => 1));

$array['IL'] = array(
	'locale' => array(
		'he_IL' => 1,
		'iw_IL' => 1),
	'tz' => array('Asia/Jerusalem' => 1));

$array['IN'] = array(
	'locale' => array(
		'ar_IN' => 1,
		'as_IN' => 1,
		'bn_IN' => 1,
		'en_IN' => 1,
		'gu_IN' => 1,
		'hi_IN' => 1,
		'kn_IN' => 1,
		'mai_IN' => 1,
		'ml_IN' => 1,
		'mr_IN' => 1,
		'or_IN' => 1,
		'pa_IN' => 1,
		'ta_IN' => 1,
		'te_IN' => 1),
	'tz' => array('Asia/Calcutta' => 1));

$array['IQ'] = array(
	'default' => 'ar_IQ',
	'locale' => array('ar_IQ' => 1),
	'tz' => array('Asia/Baghdad' => 1));

$array['IR'] = array(
	'default' => 'fa_IR',
	'locale' => array('fa_IR' => 1),
	'tz' => array('Asia/Tehran' => 1));

$array['IS'] = array(
	'default' => 'is_IS',
	'locale' => array('is_IS' => 1),
	'tz' => array('Atlantic/Reykjavik' => 1));

$array['IT'] = array(
	'default' => 'it_IT',
	'locale' => array(
		'ca_IT' => 1,
		'it_IT' => 1),
	'tz' => array('Europe/Rome' => 1));

$array['JO'] = array(
	'default' => 'ar_JO',
	'locale' => array('ar_JO' => 1),
	'tz' => array('Asia/Amman' => 1));

$array['JP'] = array(
	'default' => 'ja_JP',
	'locale' => array('ja_JP' => 1),
	'tz' => array(
		'Antarctica/Syowa' => 1,
		'Asia/Tokyo' => 1));

$array['KE'] = array(
	'locale' => array(
		'om_KE' => 1,
		'so_KE' => 1),
	'tz' => array('Africa/Nairobi' => 1));

$array['KG'] = array(
	'default' => 'ky_KG',
	'locale' => array('ky_KG' => 1),
	'tz' => array('Asia/Bishkek' => 1));

$array['KH'] = array(
	'default' => 'km_KH',
	'locale' => array('km_KH' => 1),
	'tz' => array('Asia/Phnom_Penh' => 1));

$array['KR'] = array(
	'default' => 'ko_KR',
	'locale' => array('ko_KR' => 1),
	'tz' => array('Asia/Seoul' => 1));

$array['KW'] = array(
	'default' => 'ar_KW',
	'locale' => array('ar_KW' => 1),
	'tz' => array('Asia/Kuwait' => 1));

$array['KZ'] = array(
	'default' => 'kk_KZ',
	'locale' => array('kk_KZ' => 1),
	'tz' => array(
		'Asia/Almaty' => 1,
		'Asia/Aqtau' => 1,
		'Asia/Aqtobe' => 1,
		'Asia/Oral' => 1,
		'Asia/Qyzylorda' => 1));

$array['LA'] = array(
	'default' => 'lo_LA',
	'locale' => array('lo_LA' => 1),
	'tz' => array('Asia/Vientiane' => 1));

$array['LB'] = array(
	'default' => 'ar_LB',
	'locale' => array('ar_LB' => 1),
	'tz' => array('Asia/Beirut' => 1));

$array['LK'] = array(
	'default' => 'si_LK',
	'locale' => array('si_LK' => 1),
	'tz' => array('Asia/Colombo' => 1));

$array['LR'] = array(
	'default' => 'en_LR',
	'locale' => array('en_LR' => 1),
	'tz' => array('Africa/Monrovia' => 1));

$array['LS'] = array(
	'default' => 'st_LS',
	'locale' => array(
		'st_LS' => 1,
		'en_LS' => 1),
	'tz' => array('Africa/Maseru' => 1));

$array['LT'] = array(
	'default' => 'lt_LT',
	'locale' => array('lt_LT' => 1),
	'tz' => array('Europe/Vilnius' => 1));

$array['LU'] = array(
	'locale' => array(
		'de_LU' => 1,
		'fr_LU' => 1),
	'tz' => array('Europe/Luxembourg' => 1));

$array['LV'] = array(
	'default' => 'lv_LV',
	'locale' => array('lv_LV' => 1),
	'tz' => array('Europe/Riga' => 1));

$array['LY'] = array(
	'default' => 'ar_LY',
	'locale' => array('ar_LY' => 1),
	'tz' => array('Africa/Tripoli' => 1));

$array['MA'] = array(
	'default' => 'ar_MA',
	'locale' => array('ar_MA' => 1),
	'tz' => array('Africa/Casablanca' => 1));

$array['ME'] = array(
	'default' => 'sr_ME',
	'locale' => array('sr_ME' => 1));

$array['MG'] = array(
	'default' => 'mg_MG',
	'locale' => array('mg_MG' => 1),
	'tz' => array('Indian/Antananarivo' => 1));

$array['MK'] = array(
	'default' => 'mk_MK',
	'locale' => array('mk_MK' => 1));

$array['MN'] = array(
	'default' => 'mn_MN',
	'locale' => array('mn_MN' => 1),
	'tz' => array(
		'Asia/Choibalsan' => 1,
		'Asia/Hovd' => 1,
		'Asia/Ulaanbaatar' => 1));

$array['MR'] = array(
	'default' => 'ar_MR',
	'locale' => array(
		'ar_MR' => 1,
		'fr_MR' => 1,
		'ff_MR' => 1,
		'mey_MR' => 1,
		'snk_MR' => 1,
		'wo_MR' => 1),
	'tz' => array('Africa/Nouakchott' => 1));

$array['MT'] = array(
	'default' => 'mt_MT',
	'locale' => array('mt_MT' => 1),
	'tz' => array('Europe/Malta' => 1));

$array['MW'] = array(
	'default' => 'en_MW',
	'locale' => array(
		'en_MW' => 1,
		'ny_MW' => 1),
	'tz' => array('Africa/Blantyre' => 1));

$array['MX'] = array(
	'default' => 'es_MX',
	'locale' => array('es_MX' => 1),
	'tz' => array(
		'America/Cancun' => 1,
		'America/Chihuahua' => 1,
		'America/Hermosillo' => 1,
		'America/Mazatlan' => 1,
		'America/Merida' => 1,
		'America/Mexico_City' => 1,
		'America/Monterrey' => 1,
		'America/Tijuana' => 1));

$array['MY'] = array(
	'default' => 'ms_MY',
	'locale' => array('ms_MY' => 1),
	'tz' => array(
		'Asia/Kuala_Lumpur' => 1,
		'Asia/Kuching' => 1));

$array['NI'] = array(
	'default' => 'es_NI',
	'locale' => array('es_NI' => 1),
	'tz' => array('America/Managua' => 1));

$array['NL'] = array(
	'default' => 'nl_NL',
	'locale' => array(
		'nl_NL' => 1,
		'fy_NL' => 1),
	'tz' => array('Europe/Amsterdam' => 1));

$array['NO'] = array(
	'locale' => array(
		'nb_NO' => 1,
		'nn_NO' => 1,
		'se_NO' => 1),
	'tz' => array('Europe/Oslo' => 1));

$array['NP'] = array(
	'default' => 'ne_NP',
	'locale' => array('ne_NP' => 1),
	'tz' => array('Asia/Katmandu' => 1));

$array['NZ'] = array(
	'locale' => array(
		'en_NZ' => 1,
		'mi_NZ' => 1),
	'tz' => array(
		'Pacific/Auckland' => 1,
		'Pacific/Chatham' => 1));

$array['OM'] = array(
	'default' => 'ar_OM',
	'locale' => array('ar_OM' => 1),
	'tz' => array('Asia/Muscat' => 1));

$array['PA'] = array(
	'default' => 'es_PA',
	'locale' => array('es_PA' => 1),
	'tz' => array('America/Panama' => 1));

$array['PE'] = array(
	'default' => 'es_PE',
	'locale' => array('es_PE' => 1),
	'tz' => array('America/Lima' => 1));

$array['PH'] = array(
	'locale' => array(
		'en_PH' => 1,
		'tl_PH' => 1),
	'tz' => array('Asia/Manila' => 1));

$array['PK'] = array(
	'locale' => array(
		'pa_PK' => 1,
		'ur_PK' => 1),
	'tz' => array('Asia/Karachi' => 1));

$array['PL'] = array(
	'default' => 'pl_PL',
	'locale' => array(
		'pl_PL' => 1,
		'csb_PL' => 1),
	'tz' => array('Europe/Warsaw' => 1));

$array['PR'] = array(
	'default' => 'es_PR',
	'locale' => array('es_PR' => 1),
	'tz' => array('America/Puerto_Rico' => 1));

$array['PT'] = array(
	'default' => 'pt_PT',
	'locale' => array('pt_PT' => 1),
	'tz' => array(
		'Atlantic/Azores' => 1,
		'Atlantic/Madeira' => 1,
		'Europe/Lisbon' => 1));

$array['PY'] = array(
	'default' => 'es_PY',
	'locale' => array('es_PY' => 1),
	'tz' => array('America/Asuncion' => 1));

$array['QA'] = array(
	'default' => 'ar_QA',
	'locale' => array('ar_QA' => 1),
	'tz' => array('Asia/Qatar' => 1));

$array['RO'] = array(
	'default' => 'ro_RO',
	'locale' => array('ro_RO' => 1),
	'tz' => array('Europe/Bucharest' => 1));

$array['RS'] = array(
	'default' => 'sr_RS',
	'locale' => array('sr_RS' => 1),
	'tz' => array('Europe/Belgrade' => 1));

$array['RU'] = array(
	'default' => 'ru_RU',
	'locale' => array(
		'ru_RU' => 1,
		'tt_RU' => 1),
	'tz' => array(
		'Antarctica/Vostok' => 1,
		'Asia/Anadyr' => 1,
		'Asia/Irkutsk' => 1,
		'Asia/Kamchatka' => 1,
		'Asia/Krasnoyarsk' => 1,
		'Asia/Magadan' => 1,
		'Asia/Novosibirsk' => 1,
		'Asia/Omsk' => 1,
		'Asia/Sakhalin' => 1,
		'Asia/Vladivostok' => 1,
		'Asia/Yakutsk' => 1,
		'Asia/Yekaterinburg' => 1,
		'Europe/Kaliningrad' => 1,
		'Europe/Moscow' => 1,
		'Europe/Samara' => 1,
		'Europe/Volgograd' => 1));

$array['RW'] = array(
	'default' => 'rw_RW',
	'locale' => array('rw_RW' => 1),
	'tz' => array('Africa/Kigali' => 1));

$array['SA'] = array(
	'default' => 'ar_SA',
	'locale' => array('ar_SA' => 1),
	'tz' => array('Asia/Riyadh' => 1));

$array['SD'] = array(
	'default' => 'ar_SD',
	'locale' => array('ar_SD' => 1),
	'tz' => array('Africa/Khartoum' => 1));

$array['SE'] = array(
	'default' => 'sv_SE',
	'locale' => array('sv_SE' => 1),
	'tz' => array('Europe/Stockholm' => 1));

$array['SG'] = array(
	'locale' => array(
		'en_SG' => 1,
		'zh_SG' => 1),
	'tz' => array('Asia/Singapore' => 1));

$array['SI'] = array(
	'default' => 'sl_SI',
	'locale' => array('sl_SI' => 1));

$array['SK'] = array(
	'default' => 'sk_SK',
	'locale' => array('sk_SK' => 1));

$array['SN'] = array(
	'default' => 'fr_SN',
	'locale' => array(
		'fr_SN' => 1,
		'ff_SN' => 1,
		'man_SN' => 1,
		'wo_SN' => 1),
	'tz' => array('Africa/Dakar' => 1));

$array['SO'] = array(
	'default' => 'so_SO',
	'locale' => array('so_SO' => 1),
	'tz' => array('Africa/Mogadishu' => 1));

$array['SV'] = array(
	'default' => 'es_SV',
	'locale' => array('es_SV' => 1),
	'tz' => array('America/El_Salvador' => 1));

$array['SY'] = array(
	'default' => 'ar_SY',
	'locale' => array('ar_SY' => 1),
	'tz' => array('Asia/Damascus' => 1));

$array['TD'] = array(
	'default' => 'ar_TD',
	'locale' => array(
		'ar_TD' => 1,
		'fr_TD' => 1),
	'tz' => array('Africa/Ndjamena' => 1));

$array['TH'] = array(
	'default' => 'th_TH',
	'locale' => array('th_TH' => 1),
	'tz' => array('Asia/Bangkok' => 1));

$array['TJ'] = array(
	'default' => 'tg_TJ',
	'locale' => array('tg_TJ' => 1),
	'tz' => array('Asia/Dushanbe' => 1));

$array['TN'] = array(
	'default' => 'ar_TN',
	'locale' => array('ar_TN' => 1),
	'tz' => array('Africa/Tunis' => 1));

$array['TR'] = array(
	'default' => 'tr_TR',
	'locale' => array(
		'ku_TR' => 1,
		'tr_TR' => 1),
	'tz' => array('Europe/Istanbul' => 1));

$array['TW'] = array(
	'default' => 'zh_TW',
	'locale' => array('zh_TW' => 1),
	'tz' => array('Asia/Taipei' => 1));

$array['UA'] = array(
	'locale' => array(
		'ru_UA' => 1,
		'uk_UA' => 1,
		'crh_UA' => 1),
	'tz' => array(
		'Europe/Kiev' => 1,
		'Europe/Simferopol' => 1,
		'Europe/Uzhgorod' => 1,
		'Europe/Zaporozhye' => 1));

$array['UG'] = array(
	'default' => 'lg_UG',
	'locale' => array('lg_UG' => 1),
	'tz' => array('Africa/Kampala' => 1));

$array['US'] = array(
	'locale' => array(
		'en_US' => 1,
		'es_US' => 1,
		'yi_US' => 1),
	'tz' => array(
		'America/Adak' => 1,
		'America/Anchorage' => 1,
		'America/Boise' => 1,
		'America/Chicago' => 1,
		'America/Denver' => 1,
		'America/Detroit' => 1,
		'America/Indiana/Indianapolis' => 1,
		'America/Indiana/Knox' => 1,
		'America/Indiana/Marengo' => 1,
		'America/Indiana/Petersburg' => 1,
		'America/Indiana/Vevay' => 1,
		'America/Indiana/Vincennes' => 1,
		'America/Indiana/Winamac' => 1,
		'America/Juneau' => 1,
		'America/Kentucky/Louisville' => 1,
		'America/Kentucky/Monticello' => 1,
		'America/Los_Angeles' => 1,
		'America/Menominee' => 1,
		'America/New_York' => 1,
		'America/Nome' => 1,
		'America/North_Dakota/Center' => 1,
		'America/North_Dakota/New_Salem' => 1,
		'America/Phoenix' => 1,
		'America/Shiprock' => 1,
		'America/Yakutat' => 1,
		'Antarctica/McMurdo' => 1,
		'Antarctica/Palmer' => 1,
		'Antarctica/South_Pole' => 1,
		'Pacific/Honolulu' => 1));

$array['UY'] = array(
	'default' => 'es_UY',
	'locale' => array('es_UY' => 1),
	'tz' => array('America/Montevideo' => 1));

$array['UZ'] = array(
	'default' => 'uz_UZ',
	'locale' => array('uz_UZ' => 1),
	'tz' => array(
		'Asia/Samarkand' => 1,
		'Asia/Tashkent' => 1));

$array['VE'] = array(
	'default' => 'es_VE',
	'locale' => array('es_VE' => 1),
	'tz' => array('America/Caracas' => 1));

$array['VN'] = array(
	'default' => 'vi_VN',
	'locale' => array('vi_VN' => 1),
	'tz' => array('Asia/Saigon' => 1));

$array['YE'] = array(
	'default' => 'ar_YE',
	'locale' => array('ar_YE' => 1),
	'tz' => array('Asia/Aden' => 1));

$array['ZA'] = array(
	'locale' => array(
		'af_ZA' => 1,
		'en_ZA' => 1,
		'nr_ZA' => 1,
		'nso_ZA' => 1,
		'ss_ZA' => 1,
		'st_ZA' => 1,
		'tn_ZA' => 1,
		'ts_ZA' => 1,
		've_ZA' => 1,
		'xh_ZA' => 1,
		'zu_ZA' => 1),
	'tz' => array('Africa/Johannesburg' => 1));

$array['ZW'] = array(
	'default' => 'en_ZW',
	'locale' => array('en_ZW' => 1),
	'tz' => array('Africa/Harare' => 1));

?>
