#!/bin/sh

# Xivo 0.3 - Handle dropbear SSH server.
# Copyright (C) 2006 Richard Braun <rbraun@proformatique.com>
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

set -e

PATH=/sbin:/bin:/usr/sbin:/usr/bin
pidfile=/var/run/dropbear.pid
binpath=/usr/sbin/dropbear
rsakeyfile=/etc/dropbear/dropbear_rsa_host_key
dsskeyfile=/etc/dropbear/dropbear_dss_host_key

test -x $binpath || exit 0
export PATH

# usage: running <pidfile>
running()
{
  if [ -f "$1" ]; then
    return 0
  fi

  return 1
}

check_keys()
{
  if [ ! -f $rsakeyfile ]; then
    echo "generating new RSA key..."
    dropbearkey -t rsa -f $rsakeyfile
    echo "done"
  fi

  if [ ! -f $dsskeyfile ]; then
    echo "generating new DSS key..."
    dropbearkey -t dss -f $dsskeyfile
    echo "done"
  fi
}

start_dropbear()
{
  check_keys
  echo -n "starting dropbear... "
  if ! running $pidfile; then
    start-stop-daemon -b \
                      -q \
                      -x $binpath \
                      -p $pidfile \
                      -m \
                      -S \
                      -- \
                      -F
    echo "done"
  else
    echo "dropbear already running"
  fi
}

stop_dropbear()
{
  echo -n "stopping dropbear... "
  if running $pidfile; then
    start-stop-daemon -q \
                      -x $binpath \
                      -p $pidfile \
                      -K
    sleep 1
    rm -f $pidfile
    echo "done"
  else
    echo "dropbear not running"
  fi
}

case "$1" in
  start)
    start_dropbear
    ;;
  stop)
    stop_dropbear
    ;;
  restart)
    stop_dropbear
    start_dropbear
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
