#!/bin/sh

# Xivo 0.3 - Handle crond.
# Copyright (C) 2006 Richard Braun <rbraun@proformatique.com>
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

set -e

PATH=/sbin:/bin:/usr/sbin:/usr/bin
pidfile=/var/run/crond.pid
binpath=/usr/sbin/crond

test -x $binpath || exit 0

# usage: running <pidfile>
running()
{
  if [ -f "$1" ]; then
    return 0
  fi

  return 1
}

start_crond()
{
  echo -n "starting crond... "
  if ! running $pidfile; then
    start-stop-daemon -b \
                      -q \
                      -x $binpath \
                      -p $pidfile \
                      -m \
                      -S
    echo "done"
  else
    echo "crond already running"
  fi
}

stop_crond()
{
  echo -n "stopping crond... "
  if running $pidfile; then
    start-stop-daemon -q \
                      -x $binpath \
                      -p $pidfile \
                      -K
    sleep 1
    rm -f $pidfile
    echo "done"
  else
    echo "crond not running"
  fi
}

reload_crond()
{
  echo -n "reloading crond... "
  if running $pidfile; then
    start-stop-daemon -q \
                      -x $binpath \
                      -p $pidfile \
                      -s 1 \
                      -K
    echo "done"
  else
    echo "crond not running"
  fi
}

case "$1" in
  start)
    start_crond
    ;;
  stop)
    stop_crond
    ;;
  reload)
    reload_crond
    ;;
  restart)
    stop_crond
    start_crond
    ;;
  *)
    echo "usage: $0 {start|stop|reload|restart}"
    exit 1
    ;;
esac

exit 0
