#!/bin/sh

set -x

MYSQL_BIN="mysql"
MYSQL_ETC_PATH="/etc/mysql"
MYSQL_CNF_FILE="${MYSQL_ETC_PATH}/pf-root.cnf"
MYSQL_CMD="${MYSQL_BIN} --defaults-extra-file=${MYSQL_CNF_FILE}"


### Config Setup

MYSQL_AST_STRING="mysql://asterisk:proformatique@localhost/asterisk?charset=utf8"
MYSQL_XIVO_STRING="mysql://xivo:proformatique@localhost/xivo?charset=utf8"

sed -i -r "s#^(datastorage *= *\"?)sqlite:/[^\"]+(\")?\$#\1${MYSQL_AST_STRING}\2#" /etc/pf-xivo/web-interface/ipbx.ini
sed -i -r "s#^(datastorage *= *\"?)sqlite:/[^\"]+(\")?\$#\1${MYSQL_XIVO_STRING}\2#" /etc/pf-xivo/web-interface/xivo.ini
sed -i -r "s#^(database_uri *= *\"?)sqlite:/[^\"]+(\")?\$#\1${MYSQL_AST_STRING}\2#" /etc/pf-xivo/provisioning.conf
# deactivated until pf-asternic-stats is ready for MySQL support
#sed -i -r "s#^(ctilog *= *\"?)sqlite:/[^\"]+(\")?\$#\1${MYSQL_XIVO_STRING}\2#" /etc/asterisk/xivo_daemon.conf
sed -i -r "s#^(cdr_db_uri *= *\"?)sqlite:/[^\"]+(\")?\$#\1${MYSQL_AST_STRING}\2#" /etc/asterisk/xivo_daemon.conf
sed -i -r "s#^(userfeatures_db_uri *= *\"?)sqlite:/[^\"]+(\")?\$#\1${MYSQL_AST_STRING}\2#" /etc/asterisk/xivo_daemon.conf
sed -i -r "s#^(db_uri *= *\"?)sqlite:/[^\"]+(\")?\$#\1${MYSQL_AST_STRING}\2#" /etc/pf-xivo/agid.conf

sed -i -r 's/^pre(load +=> +res_config_sqlite.so)/no\1/' /etc/asterisk/modules.conf
if grep -q "res_config_mysql" /etc/asterisk/modules.conf; then
  sed -i -r 's/^no(load +=> +res_config_mysql.so)/\1/' /etc/asterisk/modules.conf
else
  echo "load => res_config_mysql.so" >>/etc/asterisk/modules.conf
fi

sed -i -r 's/sqlite/mysql/g' /etc/asterisk/extconfig.conf

