#ifndef __POPUP_H__
#define __POPUP_H__

#include <QWidget>
#include <QIODevice>
#include <QVBoxLayout>
#include <QTcpSocket>
#include "xmlhandler.h"

/*! \brief Profile popup widget
 *
 * Constructed from the message received */
class Popup: public QWidget
{
	Q_OBJECT
public:
	//! Construct from a QIODevice used to read XML input
	Popup(QIODevice *inputstream, const QString & sessionid, QWidget *parent=0);
	//! Add a Text field (name, value)
	void addInfoText(const QString & name, const QString & value);
	//! Add a url field
	void addInfoLink(const QString & name, const QString & value);
	//! Add a Picture
	void addInfoPicture(const QString & name, const QString & value);
	//! Add a Phone number
	void addInfoPhone(const QString & name, const QString & value);
	//! finalize the Construction of the window and show it
	void finishAndShow();
signals:
	void wantsToBeShown(Popup *);	//!< sent when the widget want to show itself
public slots:
	void streamNewData();		//!< new input data is available
	void streamAboutToClose();	//!< catch aboutToClose() signal from the socket
	void socketDisconnected();	//!< connected to disconnected() signal
	void socketError(QAbstractSocket::SocketError err);	//!< socket error handling
protected:
	void closeEvent(QCloseEvent *event);	//!< catch close event
private:
	QIODevice * m_inputstream;	//!< input stream where the XML is read from
	/* the following properties are for XML parsing */
	//! QXmlInputSource constructed from m_inputstream
	QXmlInputSource m_xmlInputSource;
	//! XML parser object.
	QXmlSimpleReader m_reader;
	//! Handler for event generated by the XML parser
	XmlHandler m_handler;
	//! Is the XML already started or not ?
	bool m_parsingStarted;
	//! layout for the widget : vertical box
	QVBoxLayout * m_vlayout;
	//! Session id with the server in order to check the incoming message
	QString m_sessionid;
};

#endif

