#!/usr/bin/make -f
# -*- mode: makefile; coding: utf-8 -*-
#
# $Revision$
# $Date$

include $(NONO_MK)/autobuild.mk
include $(NONO_MK)/autobuild-classic.mk

DEB_PKG="pf-xivo-lib-python"
DEB_TB_DEPS=""
DEB_TAR_EXTRA_OPTIONS=--exclude="*.pyc" --exclude=Experimentations --exclude=Todo --exclude=old

default:

