#!/usr/bin/make -f
# -*- mode: makefile; coding: utf-8 -*-
#
# $Revision$
# $Date$

include ../autobuild.mk
include ../autobuild-classic.mk

DEB_PKG="pf-xivo-provisioning"
DEB_TB_DEPS=""
DEB_TAR_EXTRA_OPTIONS="--exclude=*.pyc"

default:

