#!/usr/bin/make -f
# -*- mode: makefile; coding: utf-8 -*-
#
# $Revision$
# $Date$

include $(WRK_DIR)/../autobuild.mk
include $(WRK_DIR)/../autobuild-classic.mk

DEB_PKG="pf-xivo-cti-pushagi"
DEB_TAR_EXTRA_OPTIONS="--exclude=*.py"

default:

prepare-tarball::

clean-tarball::
	@rm -f xivo_push

