#!/usr/bin/make -f
# -*- mode: makefile; coding: utf-8 -*-
#
# $Revision$
# $Date$

include $(NONO_MK)/autobuild.mk
include $(NONO_MK)/autobuild-classic.mk


DEB_PKG="pf-xivo-cti-pushagi"
DEB_TAR_EXTRA_OPTIONS="--exclude=*.py"
TARBALL_DIR = $(realpath .)

default:

prepare-tarball::

clean-tarball::
	@rm -f xivo_push

