#! /usr/bin/python
# vim: set fileencoding=utf-8 :
#
# $Revision$
# $Date$
#
# Authors : Thomas Bernard, Corentin Le Gall, Sylvain Boily
#           Proformatique
#           67, rue Voltaire
#           92800 PUTEAUX
#           (+33/0)1.41.38.99.60
#           mailto:technique@proformatique.com
#           (C) 2007 Proformatique
#
# AGI de push de fiche
#

import xivo.to_path
import ConfigParser
import os
import pickle
import re
import sys
import socket
from agi import *

agi = AGI()

## \brief Logs a message into the Asterisk CLI
# \param txt message to send to the CLI
def print_verbose(txt):
        agi.verbose("push_callbooster : %s" % txt)

def findpath(acc, mfile):
        fullfile = '%s/%s/%s/Sons/%s.wav' % (path_sounds_asterisk, path_sounds_callbooster, '/'.join(acc), mfile)
        partfile = '%s/Sons/%s' % ('/'.join(acc), mfile)
        if os.path.exists(fullfile):
                return [acc, partfile]
        else:
                if len(acc) == 3:
                        if acc[2] != '0':
                                tacc = [acc[0], acc[1], '0']
                        else:
                                tacc = [acc[0], acc[1]]
                elif len(acc) == 2:
                        if acc[1] != '0':
                                tacc = [acc[0], '0']
                        else:
                                tacc = [acc[0]]
                elif len(acc) == 1:
                        if acc[0] != '0':
                                tacc = ['0']
                        else:
                                tacc = []

                if len(acc) > 0:
                        [nacc, npartfile] = findpath(tacc, mfile)
                else:
                        [nacc, npartfile] = [None, None]
                return [nacc, npartfile]



# ==============================================================================
# Main Code starts here
# ==============================================================================

CONFIG_XIVO_DAEMON = '/etc/xivo/xivo_fb.conf'

port_comm_agi_daemon = 4970
path_sounds_asterisk = '/var/lib/asterisk/sounds'
path_sounds_callbooster = 'fr/callbooster'

xivocfg = ConfigParser.ConfigParser()
try:
        xivocfg.readfp(open(CONFIG_XIVO_DAEMON))
        xivocfg_general = dict(xivocfg.items('general'))
        if 'port_comm_agi_daemon' in xivocfg_general:
                port_comm_agi_daemon = int(xivocfg_general.get('port_comm_agi_daemon'))
        if 'path_sounds_asterisk' in xivocfg_general:
                path_sounds_asterisk = int(xivocfg_general.get('path_sounds_asterisk'))
        if 'path_sounds_callbooster' in xivocfg_general:
                path_sounds_callbooster = int(xivocfg_general.get('path_sounds_callbooster'))
except Exception, exc:
        print_verbose('could not access to config in %s (err = %s) : default config used' % (CONFIG_XIVO_DAEMON, str(exc)))


action = 'exit'
mysda = sys.argv[1]
print_verbose('in callbooster AGI <%s>' % mysda)

cidnum    = agi.env['agi_callerid']
prevwhere = agi.get_variable('CB_AGI_WHERE')
inchannel = agi.get_variable('CHANNEL')
if prevwhere == '':
        upto = '0'
else:
        upto = prevwhere

try:
        s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        s.connect(('127.0.0.1', port_comm_agi_daemon))
        s.send('PUSH <%s> <%s> <%s> <%s>\r\n' % (inchannel, cidnum, mysda, upto))
        pushreply = s.recv(8192)
        # print_verbose('before pickle loads : <%s>' % str(pushreply))
        # format PULL_START (struct) PULL_STOP
        try:
                n = pickle.loads(pushreply[11:-10])
        except Exception, exc:
                n = None
                print_verbose('could not pickle.loads the answer from daemon')
        # print_verbose('pickle loads : %s' % str(n))
        if n is not None:
                action = n['action']
                delay  = n['delay']
                argum  = n['argument']
                where  = n['newupto']
                queuename = n['queuename']
                dialplan = n['dialplan']
                print_verbose('%s %s %s %s %s : %s' % (action, delay, argum, where, queuename, str(dialplan)))
        else:
                action = 'exit'
                delay  = 0
                print_verbose('could not unpickle the reply : set CB_AGI_STATUS to exit')
except Exception, exc:
        action = 'exit'
        delay  = 0
        print_verbose('could not connect to daemon : %s' % str(exc))


# sets the action before further treatment (in order for dialplan to end in the exit case)
agi.set_variable('CB_AGI_STATUS', action)

print_verbose('CB : received ACTION=%s WAIT=%ds ARG=%s WHERE=%s QUEUENAME=%s' %(action, int(delay), argum, where, queuename))

if action == 'sec':
        if argum is None:
                agi.set_variable('CB_FIRST_WELCOME', 'already')

if action == 'tel' or action == 'bas' or action == 'fic':
        telargs = argum.split('-')
        agi.set_variable('CB_AGI_TEL_NUM', telargs[0])
        agi.set_variable('CB_AGI_TEL_DELAY', telargs[1])
        agi.set_variable('CB_AGI_TEL_CHERCHE', telargs[2])
        agi.set_variable('CB_AGI_TEL_PATIENTE', telargs[3])

if action == 'rep':
        agi.set_variable('CB_AGI_ARG', argum)

if action == 'mes':
        argums = argum.split(';')
        agi.set_variable('CB_AGI_MES_MES', argums[0])
        agi.set_variable('CB_AGI_MES_SDA', mysda)

if 'dialplan' is not None:
        if dialplan['record'] is not None:
                agi.set_variable('CB_AGI_RECORD', dialplan['record'])
        if 'soundpath' in dialplan:
                acc = dialplan['soundpath'].split('/')

                [fpath, partfile] = findpath(acc, dialplan['M001003'])
                if partfile is not None:
                        agi.set_variable('CB_AGI_MES_WELCOME', partfile)
                else:
                        print_verbose('CB_AGI_MES_WELCOME (%s) : %s does not exist on filesystem' % (str(acc), dialplan['M001003']))

                for mfile in ['M002', 'M005', 'M006', 'M007', 'M008', 'M009', 'M012', 'M025']:
                        if mfile in dialplan['sounds']:
                                [fpath, partfile] = findpath(acc, mfile)
                                if partfile is not None:
                                        agi.set_variable('CB_AGI_MES_%s' % mfile, partfile)
                                else:
                                        print_verbose('CB_AGI_MES_%s (%s) : does not exist on filesystem' % (mfile, str(acc)))
                if 'M018' in dialplan['sounds']:
                        agi.set_variable('CB_AGI_MES_WAITINGMUSIC', dialplan['soundpath'])


# saving the current CB 'dialplan' position and status, might be useful for true dialplan decisions
agi.set_variable('CB_AGI_WHERE', where)

# setting the Queue() to call
agi.set_variable('CB_AGI_QUEUE_NAME', queuename)
# delay to set for Queue()
agi.set_variable('CB_AGI_QUEUE_WAIT', delay)
