#!/usr/bin/make -f
# -*- mode: makefile; coding: utf-8 -*-
#
# $Revision$
# $Date$

include $(NONO_MK)/autobuild.mk
include $(NONO_MK)/autobuild-classic.mk

DEB_PKG := python-cjson
TARBALL_DIR := $(realpath $(MODULE_PATH)/python-cjson)
MAINREV := $(shell cat $(realpath $(MODULE_PATH))/VERSION)
SVNREV := $(shell svn info $(TARBALL_DIR) | grep "Last Changed Rev" | sed "s/.*: //")
XIVO_REV := $(MAINREV)~svn$(SVNREV)

default:
