<?php

define('XIVO_LABEL','XIVO-WEBI');

define('XIVO_SOFT_NAME','xivo');
define('XIVO_SOFT_LABEL','XIVO');
define('XIVO_SOFT_VERSION','0.4');
define('XIVO_SOFT_CODENAME','K-9');
define('XIVO_SOFT_URL','www.xivo.fr');
define('XIVO_CORP_NAME','proformatique');
define('XIVO_CORP_LABEL','Proformatique');
define('XIVO_CORP_EMAIL','contact@proformatique.com');
define('XIVO_CORP_URL','www.proformatique.com');
define('XIVO_CORP_ADDRESS','67 rue Voltaire');
define('XIVO_CORP_ZIPCODE','92800');
define('XIVO_CORP_CITY','Puteaux');
define('XIVO_CORP_COUNTRY','France');
define('XIVO_CORP_PHONE','+33 (0) 1 41 38 99 60');
define('XIVO_CORP_FAX','+33 (0) 1 41 38 99 70');

?>
