<?php

#
# XiVO Web-Interface
# Copyright (C) 2006-2009  Proformatique <technique@proformatique.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

define('XIVO_LABEL','XIVO-WEBI');

define('XIVO_SOFT_NAME','xivo');
define('XIVO_SOFT_LABEL','XIVO');
define('XIVO_SOFT_VERSION','1.1');
define('XIVO_SOFT_CODENAME','Gallifrey');
define('XIVO_SOFT_URL','xivo.fr');
define('XIVO_CORP_NAME','proformatique');
define('XIVO_CORP_LABEL','Proformatique');
define('XIVO_CORP_EMAIL','contact@proformatique.com');
define('XIVO_CORP_URL','proformatique.com');
define('XIVO_CORP_ADDRESS','10 bis, rue Lucien VOILIN');
define('XIVO_CORP_ZIPCODE','92800');
define('XIVO_CORP_CITY','Puteaux');
define('XIVO_CORP_COUNTRY','France');
define('XIVO_CORP_PHONE','+33 (0) 1 41 38 99 60');
define('XIVO_CORP_FAX','+33 (0) 1 41 38 99 70');

?>
