#!/usr/bin/python
# $Revision: 593 $
# $Date: 2007-05-15 11:17:20 +0200 (mar, 15 mai 2007) $
#
# Authors : Sylvain Boily, Guillaume Knispel
#           Proformatique
#           67, rue Voltaire
#           92800 PUTEAUX
#           (+33/0)1.41.38.99.60
#           mailto:technique@proformatique.com
#           (C) 2007 Proformatique
#

import ConfigParser, string, sys

try:
        exten = sys.argv[1]
except:
        exten = ""

ring = "/etc/asterisk/ring.conf"

config = ConfigParser.ConfigParser()
config.readfp(open(ring))

#phonetype = config.get('number', exten)
phonetype = 'thomson'

sys.stdout.write("SET VARIABLE RINGINTERNAL \"" + config.get(phonetype, 'intern') + "\"\n")
sys.stdout.write("SET VARIABLE RINGEXTERNAL \"" + config.get(phonetype, 'extern') + "\"\n")
sys.stdout.write("SET VARIABLE RINGGROUP \"" + config.get(phonetype, 'group') + "\"\n")

if phonetype == 'thomson':
	sys.stdout.write("SET VARIABLE ISTHOMSON 1\n")

sys.stdout.flush()
sys.stderr.flush()
