<?php

#
# XiVO Web-Interface
# Copyright (C) 2009-2010  Proformatique <technique@proformatique.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

$array = array();

$array['module'] = array();

$array['module']['accesswebservice'] = array();
$array['module']['accesswebservice']['datastorage'] = true;

$array['module']['entity'] = array();
$array['module']['entity']['datastorage'] = true;

$array['module']['iproute'] = array();
$array['module']['iproute']['datastorage'] = true;

$array['module']['ldapserver'] = array();
$array['module']['ldapserver']['datastorage'] = true;

$array['module']['netiface'] = array();
$array['module']['netiface']['datastorage'] = true;

$array['module']['resolvconf'] = array();
$array['module']['resolvconf']['datastorage'] = true;

$array['module']['server'] = array();
$array['module']['server']['datastorage'] = true;

?>
