<?php

#
# XiVO Web-Interface
# Copyright (C) 2010  Proformatique <technique@proformatique.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

$array = array();

$array['element'] = array();

$array['element']['maintenance'] = array();
$array['element']['maintenance']['default'] = false;

$array['element']['alert_emails'] = array();
$array['element']['alert_emails']['default'] = null;

$array['element']['dahdi_monitor_ports'] = array();
$array['element']['dahdi_monitor_ports']['default'] = null;

$array['element']['max_call_duration'] = array();
$array['element']['max_call_duration']['default'] = null;


### filters ###
#$array['filter'] = array();

?>
